name: 'Setup Rust Toolchain'
description: 'Sets up Rust with optional components, protoc, and caching'
inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: '1.88.0'
  components:
    description: 'Comma-separated list of components to install (e.g., rustfmt,clippy)'
    required: false
    default: 'rustfmt,clippy'
  install-protoc:
    description: 'Whether to install protoc'
    required: false
    default: 'true'
  cache:
    description: 'Whether to enable Rust caching with Swatinem/rust-cache'
    required: false
    default: 'true'
  target:
    description: 'Additional target to install (e.g., x86_64-unknown-linux-gnu)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        target: ${{ inputs.target }}
        cache: false

    - name: Setup Rust cache
      if: inputs.cache == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        # The prefix cache key, this can be changed to start a new cache manually.
        prefix-key: "v0-rust"

        # Use shared key based on lock file hash to ensure cache invalidation
        # when dependencies change
        shared-key: "rust-cache"
        # Cache the registry index and git checkouts to speed up builds
        cache-all-crates: "true"

    - name: Install protoc
      if: inputs.install-protoc == 'true'
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ github.token }}
