changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
    - label: Added BREAKING (Major, changes to existing API contracts)
      auto: major
    - label: Added (Minor, new features)
      auto: minor
    - label: Added (Patch, new features)
      auto: patch
    - label: Changed BREAKING (Major, changes to existing API contracts)
      auto: major
    - label: Changed (Minor, changes to existing functionality without breaking API changes)
      auto: minor
    - label: Fixed (Patch, bug fixes)
      auto: patch
    - label: Patch (Other, non-breaking changes)
      auto: patch
    - label: Removed BREAKING (Major, changes to existing API contracts)
      auto: major
    - label: Removed (Minor, removes existing functionality without breaking API contracts)
      auto: minor
    - label: CI, Docs, Test, Internal
      auto: none
      
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_

replacements:
  - path: crates/sdk-js/package.json
    find: '	"version": ".*",'
    replace: '	"version": "{{.VersionNoPrefix}}",'
  - path: crates/soma-frontend/app/package.json
    find: '	"version": ".*",'
    replace: '	"version": "{{.VersionNoPrefix}}",'
  - path: js/packages/api-client/package.json
    find: '	"version": ".*",'
    replace: '	"version": "{{.VersionNoPrefix}}",'
  - path: js/packages/sdk/package.json
    find: '	"version": ".*",'
    replace: '	"version": "{{.VersionNoPrefix}}",'
  - path: VERSION
    find: '.*'
    replace: '{{.VersionNoPrefix}}'
  - path: Cargo.toml
    find: 'version = ".*" # CHANGIE AUTOGENERATED'
    replace: 'version = "{{.VersionNoPrefix}}" # CHANGIE AUTOGENERATED'

footerFormat: |
  ### OpenAPI Schema Changes
  {{- if ne .VersionNoPrefix "" }}
  (for release version {{.VersionNoPrefix}})
  {{- end }}
  {{ .Env.OPENAPI_DIFF }}

  ### Database Schema Changes
  {{- if ne .VersionNoPrefix "" }}
  (for release version {{.VersionNoPrefix}})
  {{- end }}
  {{ .Env.DATABASE_SCHEMA_DIFF }}