/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddMcpServerInstanceFunctionRequest
 */
export interface AddMcpServerInstanceFunctionRequest {
	/**
	 *
	 * @type {string}
	 * @memberof AddMcpServerInstanceFunctionRequest
	 */
	functionControllerTypeId: string;
	/**
	 *
	 * @type {string}
	 * @memberof AddMcpServerInstanceFunctionRequest
	 */
	functionDescription?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof AddMcpServerInstanceFunctionRequest
	 */
	functionName: string;
	/**
	 *
	 * @type {string}
	 * @memberof AddMcpServerInstanceFunctionRequest
	 */
	providerControllerTypeId: string;
	/**
	 *
	 * @type {string}
	 * @memberof AddMcpServerInstanceFunctionRequest
	 */
	providerInstanceId: string;
}

/**
 * Check if a given object implements the AddMcpServerInstanceFunctionRequest interface.
 */
export function instanceOfAddMcpServerInstanceFunctionRequest(
	value: object,
): value is AddMcpServerInstanceFunctionRequest {
	if (
		!("functionControllerTypeId" in value) ||
		value.functionControllerTypeId === undefined
	)
		return false;
	if (!("functionName" in value) || value.functionName === undefined)
		return false;
	if (
		!("providerControllerTypeId" in value) ||
		value.providerControllerTypeId === undefined
	)
		return false;
	if (
		!("providerInstanceId" in value) ||
		value.providerInstanceId === undefined
	)
		return false;
	return true;
}

export function AddMcpServerInstanceFunctionRequestFromJSON(
	json: any,
): AddMcpServerInstanceFunctionRequest {
	return AddMcpServerInstanceFunctionRequestFromJSONTyped(json, false);
}

export function AddMcpServerInstanceFunctionRequestFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): AddMcpServerInstanceFunctionRequest {
	if (json == null) {
		return json;
	}
	return {
		functionControllerTypeId: json.function_controller_type_id,
		functionDescription:
			json.function_description == null ? undefined : json.function_description,
		functionName: json.function_name,
		providerControllerTypeId: json.provider_controller_type_id,
		providerInstanceId: json.provider_instance_id,
	};
}

export function AddMcpServerInstanceFunctionRequestToJSON(
	json: any,
): AddMcpServerInstanceFunctionRequest {
	return AddMcpServerInstanceFunctionRequestToJSONTyped(json, false);
}

export function AddMcpServerInstanceFunctionRequestToJSONTyped(
	value?: AddMcpServerInstanceFunctionRequest | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		function_controller_type_id: value.functionControllerTypeId,
		function_description: value.functionDescription,
		function_name: value.functionName,
		provider_controller_type_id: value.providerControllerTypeId,
		provider_instance_id: value.providerInstanceId,
	};
}
