/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BrokerActionRedirect } from "./BrokerActionRedirect";
import {
	BrokerActionRedirectFromJSON,
	BrokerActionRedirectToJSON,
} from "./BrokerActionRedirect";

/**
 *
 * @export
 * @interface BrokerActionOneOf
 */
export interface BrokerActionOneOf {
	/**
	 *
	 * @type {BrokerActionRedirect}
	 * @memberof BrokerActionOneOf
	 */
	redirect: BrokerActionRedirect;
}

/**
 * Check if a given object implements the BrokerActionOneOf interface.
 */
export function instanceOfBrokerActionOneOf(
	value: object,
): value is BrokerActionOneOf {
	if (!("redirect" in value) || value.redirect === undefined) return false;
	return true;
}

export function BrokerActionOneOfFromJSON(json: any): BrokerActionOneOf {
	return BrokerActionOneOfFromJSONTyped(json, false);
}

export function BrokerActionOneOfFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): BrokerActionOneOf {
	if (json == null) {
		return json;
	}
	return {
		redirect: BrokerActionRedirectFromJSON(json.Redirect),
	};
}

export function BrokerActionOneOfToJSON(json: any): BrokerActionOneOf {
	return BrokerActionOneOfToJSONTyped(json, false);
}

export function BrokerActionOneOfToJSONTyped(
	value?: BrokerActionOneOf | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		Redirect: BrokerActionRedirectToJSON(value.redirect),
	};
}
