/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BrokerActionOneOfRedirect
 */
export interface BrokerActionOneOfRedirect {
	/**
	 *
	 * @type {string}
	 * @memberof BrokerActionOneOfRedirect
	 */
	url: string;
}

/**
 * Check if a given object implements the BrokerActionOneOfRedirect interface.
 */
export function instanceOfBrokerActionOneOfRedirect(
	value: object,
): value is BrokerActionOneOfRedirect {
	if (!("url" in value) || value.url === undefined) return false;
	return true;
}

export function BrokerActionOneOfRedirectFromJSON(
	json: any,
): BrokerActionOneOfRedirect {
	return BrokerActionOneOfRedirectFromJSONTyped(json, false);
}

export function BrokerActionOneOfRedirectFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): BrokerActionOneOfRedirect {
	if (json == null) {
		return json;
	}
	return {
		url: json.url,
	};
}

export function BrokerActionOneOfRedirectToJSON(
	json: any,
): BrokerActionOneOfRedirect {
	return BrokerActionOneOfRedirectToJSONTyped(json, false);
}

export function BrokerActionOneOfRedirectToJSONTyped(
	value?: BrokerActionOneOfRedirect | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		url: value.url,
	};
}
