/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BrokerActionOneOf } from "./BrokerActionOneOf";
import {
	BrokerActionOneOfFromJSONTyped,
	BrokerActionOneOfToJSON,
	instanceOfBrokerActionOneOf,
} from "./BrokerActionOneOf";

/**
 * @type BrokerAction
 *
 * @export
 */
export type BrokerAction = BrokerActionOneOf | string;

export function BrokerActionFromJSON(json: any): BrokerAction {
	return BrokerActionFromJSONTyped(json, false);
}

export function BrokerActionFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): BrokerAction {
	if (json == null) {
		return json;
	}
	if (typeof json !== "object") {
		return json;
	}
	if (instanceOfBrokerActionOneOf(json)) {
		return BrokerActionOneOfFromJSONTyped(json, true);
	}

	return {} as any;
}

export function BrokerActionToJSON(json: any): any {
	return BrokerActionToJSONTyped(json, false);
}

export function BrokerActionToJSONTyped(
	value?: BrokerAction | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}
	if (typeof value !== "object") {
		return value;
	}
	if (instanceOfBrokerActionOneOf(value)) {
		return BrokerActionOneOfToJSON(value as BrokerActionOneOf);
	}

	return {};
}
