/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConfigurationSchemaItem
 */
export interface ConfigurationSchemaItem {
	/**
	 *
	 * @type {{ [key: string]: any; }}
	 * @memberof ConfigurationSchemaItem
	 */
	resourceServer: { [key: string]: any };
	/**
	 *
	 * @type {{ [key: string]: any; }}
	 * @memberof ConfigurationSchemaItem
	 */
	userCredential: { [key: string]: any };
}

/**
 * Check if a given object implements the ConfigurationSchemaItem interface.
 */
export function instanceOfConfigurationSchemaItem(
	value: object,
): value is ConfigurationSchemaItem {
	if (!("resourceServer" in value) || value.resourceServer === undefined)
		return false;
	if (!("userCredential" in value) || value.userCredential === undefined)
		return false;
	return true;
}

export function ConfigurationSchemaItemFromJSON(
	json: any,
): ConfigurationSchemaItem {
	return ConfigurationSchemaItemFromJSONTyped(json, false);
}

export function ConfigurationSchemaItemFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ConfigurationSchemaItem {
	if (json == null) {
		return json;
	}
	return {
		resourceServer: json.resource_server,
		userCredential: json.user_credential,
	};
}

export function ConfigurationSchemaItemToJSON(
	json: any,
): ConfigurationSchemaItem {
	return ConfigurationSchemaItemToJSONTyped(json, false);
}

export function ConfigurationSchemaItemToJSONTyped(
	value?: ConfigurationSchemaItem | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		resource_server: value.resourceServer,
		user_credential: value.userCredential,
	};
}
