/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ContextInfo } from "./ContextInfo";
import { ContextInfoFromJSON, ContextInfoToJSON } from "./ContextInfo";

/**
 *
 * @export
 * @interface ContextInfoPaginatedResponse
 */
export interface ContextInfoPaginatedResponse {
	/**
	 *
	 * @type {Array<ContextInfo>}
	 * @memberof ContextInfoPaginatedResponse
	 */
	items: Array<ContextInfo>;
	/**
	 *
	 * @type {string}
	 * @memberof ContextInfoPaginatedResponse
	 */
	nextPageToken?: string;
}

/**
 * Check if a given object implements the ContextInfoPaginatedResponse interface.
 */
export function instanceOfContextInfoPaginatedResponse(
	value: object,
): value is ContextInfoPaginatedResponse {
	if (!("items" in value) || value.items === undefined) return false;
	return true;
}

export function ContextInfoPaginatedResponseFromJSON(
	json: any,
): ContextInfoPaginatedResponse {
	return ContextInfoPaginatedResponseFromJSONTyped(json, false);
}

export function ContextInfoPaginatedResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ContextInfoPaginatedResponse {
	if (json == null) {
		return json;
	}
	return {
		items: (json.items as Array<any>).map(ContextInfoFromJSON),
		nextPageToken:
			json.next_page_token == null ? undefined : json.next_page_token,
	};
}

export function ContextInfoPaginatedResponseToJSON(
	json: any,
): ContextInfoPaginatedResponse {
	return ContextInfoPaginatedResponseToJSONTyped(json, false);
}

export function ContextInfoPaginatedResponseToJSONTyped(
	value?: ContextInfoPaginatedResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		items: (value.items as Array<any>).map(ContextInfoToJSON),
		next_page_token: value.nextPageToken,
	};
}
