/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ContextInfo
 */
export interface ContextInfo {
	/**
	 *
	 * @type {string}
	 * @memberof ContextInfo
	 */
	contextId: string;
	/**
	 *
	 * @type {Date}
	 * @memberof ContextInfo
	 */
	createdAt: Date;
}

/**
 * Check if a given object implements the ContextInfo interface.
 */
export function instanceOfContextInfo(value: object): value is ContextInfo {
	if (!("contextId" in value) || value.contextId === undefined) return false;
	if (!("createdAt" in value) || value.createdAt === undefined) return false;
	return true;
}

export function ContextInfoFromJSON(json: any): ContextInfo {
	return ContextInfoFromJSONTyped(json, false);
}

export function ContextInfoFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ContextInfo {
	if (json == null) {
		return json;
	}
	return {
		contextId: json.context_id,
		createdAt: new Date(json.created_at),
	};
}

export function ContextInfoToJSON(json: any): ContextInfo {
	return ContextInfoToJSONTyped(json, false);
}

export function ContextInfoToJSONTyped(
	value?: ContextInfo | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		context_id: value.contextId,
		created_at: value.createdAt.toISOString(),
	};
}
