/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateDataEncryptionKeyParamsRoute
 */
export interface CreateDataEncryptionKeyParamsRoute {
	/**
	 *
	 * @type {string}
	 * @memberof CreateDataEncryptionKeyParamsRoute
	 */
	encryptedDek?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof CreateDataEncryptionKeyParamsRoute
	 */
	id?: string | null;
}

/**
 * Check if a given object implements the CreateDataEncryptionKeyParamsRoute interface.
 */
export function instanceOfCreateDataEncryptionKeyParamsRoute(
	value: object,
): value is CreateDataEncryptionKeyParamsRoute {
	return true;
}

export function CreateDataEncryptionKeyParamsRouteFromJSON(
	json: any,
): CreateDataEncryptionKeyParamsRoute {
	return CreateDataEncryptionKeyParamsRouteFromJSONTyped(json, false);
}

export function CreateDataEncryptionKeyParamsRouteFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): CreateDataEncryptionKeyParamsRoute {
	if (json == null) {
		return json;
	}
	return {
		encryptedDek: json.encrypted_dek == null ? undefined : json.encrypted_dek,
		id: json.id == null ? undefined : json.id,
	};
}

export function CreateDataEncryptionKeyParamsRouteToJSON(
	json: any,
): CreateDataEncryptionKeyParamsRoute {
	return CreateDataEncryptionKeyParamsRouteToJSONTyped(json, false);
}

export function CreateDataEncryptionKeyParamsRouteToJSONTyped(
	value?: CreateDataEncryptionKeyParamsRoute | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		encrypted_dek: value.encryptedDek,
		id: value.id,
	};
}
