/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UserAuthFlowConfig } from "./UserAuthFlowConfig";
import {
	UserAuthFlowConfigFromJSON,
	UserAuthFlowConfigToJSON,
} from "./UserAuthFlowConfig";

/**
 * Parameters for creating a user auth flow configuration
 * @export
 * @interface CreateUserAuthFlowConfigParams
 */
export interface CreateUserAuthFlowConfigParams {
	/**
	 * The configuration to create (unencrypted)
	 * @type {UserAuthFlowConfig}
	 * @memberof CreateUserAuthFlowConfigParams
	 */
	config: UserAuthFlowConfig;
}

/**
 * Check if a given object implements the CreateUserAuthFlowConfigParams interface.
 */
export function instanceOfCreateUserAuthFlowConfigParams(
	value: object,
): value is CreateUserAuthFlowConfigParams {
	if (!("config" in value) || value.config === undefined) return false;
	return true;
}

export function CreateUserAuthFlowConfigParamsFromJSON(
	json: any,
): CreateUserAuthFlowConfigParams {
	return CreateUserAuthFlowConfigParamsFromJSONTyped(json, false);
}

export function CreateUserAuthFlowConfigParamsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): CreateUserAuthFlowConfigParams {
	if (json == null) {
		return json;
	}
	return {
		config: UserAuthFlowConfigFromJSON(json.config),
	};
}

export function CreateUserAuthFlowConfigParamsToJSON(
	json: any,
): CreateUserAuthFlowConfigParams {
	return CreateUserAuthFlowConfigParamsToJSONTyped(json, false);
}

export function CreateUserAuthFlowConfigParamsToJSONTyped(
	value?: CreateUserAuthFlowConfigParams | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		config: UserAuthFlowConfigToJSON(value.config),
	};
}
