/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MessagePart } from "./MessagePart";
import { MessagePartFromJSON, MessagePartToJSON } from "./MessagePart";
import type { MessageRole } from "./MessageRole";
import { MessageRoleFromJSON, MessageRoleToJSON } from "./MessageRole";

/**
 *
 * @export
 * @interface CreateMessageRequest
 */
export interface CreateMessageRequest {
	/**
	 *
	 * @type {{ [key: string]: any; }}
	 * @memberof CreateMessageRequest
	 */
	metadata: { [key: string]: any };
	/**
	 *
	 * @type {Array<MessagePart>}
	 * @memberof CreateMessageRequest
	 */
	parts: Array<MessagePart>;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof CreateMessageRequest
	 */
	referenceTaskIds: Array<string>;
	/**
	 *
	 * @type {MessageRole}
	 * @memberof CreateMessageRequest
	 */
	role: MessageRole;
}

/**
 * Check if a given object implements the CreateMessageRequest interface.
 */
export function instanceOfCreateMessageRequest(
	value: object,
): value is CreateMessageRequest {
	if (!("metadata" in value) || value.metadata === undefined) return false;
	if (!("parts" in value) || value.parts === undefined) return false;
	if (!("referenceTaskIds" in value) || value.referenceTaskIds === undefined)
		return false;
	if (!("role" in value) || value.role === undefined) return false;
	return true;
}

export function CreateMessageRequestFromJSON(json: any): CreateMessageRequest {
	return CreateMessageRequestFromJSONTyped(json, false);
}

export function CreateMessageRequestFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): CreateMessageRequest {
	if (json == null) {
		return json;
	}
	return {
		metadata: json.metadata,
		parts: (json.parts as Array<any>).map(MessagePartFromJSON),
		referenceTaskIds: json.reference_task_ids,
		role: MessageRoleFromJSON(json.role),
	};
}

export function CreateMessageRequestToJSON(json: any): CreateMessageRequest {
	return CreateMessageRequestToJSONTyped(json, false);
}

export function CreateMessageRequestToJSONTyped(
	value?: CreateMessageRequest | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		metadata: value.metadata,
		parts: (value.parts as Array<any>).map(MessagePartToJSON),
		reference_task_ids: value.referenceTaskIds,
		role: MessageRoleToJSON(value.role),
	};
}
