/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Parameters for creating an API key
 * @export
 * @interface CreateApiKeyParams
 */
export interface CreateApiKeyParams {
	/**
	 * Description of the API key
	 * @type {string}
	 * @memberof CreateApiKeyParams
	 */
	description?: string | null;
	/**
	 * Role to assign to the API key's user
	 * @type {string}
	 * @memberof CreateApiKeyParams
	 */
	role: string;
}

/**
 * Check if a given object implements the CreateApiKeyParams interface.
 */
export function instanceOfCreateApiKeyParams(
	value: object,
): value is CreateApiKeyParams {
	if (!("role" in value) || value.role === undefined) return false;
	return true;
}

export function CreateApiKeyParamsFromJSON(json: any): CreateApiKeyParams {
	return CreateApiKeyParamsFromJSONTyped(json, false);
}

export function CreateApiKeyParamsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): CreateApiKeyParams {
	if (json == null) {
		return json;
	}
	return {
		description: json.description == null ? undefined : json.description,
		role: json.role,
	};
}

export function CreateApiKeyParamsToJSON(json: any): CreateApiKeyParams {
	return CreateApiKeyParamsToJSONTyped(json, false);
}

export function CreateApiKeyParamsToJSONTyped(
	value?: CreateApiKeyParams | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		description: value.description,
		role: value.role,
	};
}
