/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResourceServerCredentialParamsInner
 */
export interface CreateResourceServerCredentialParamsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateResourceServerCredentialParamsInner
     */
    dataEncryptionKeyId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateResourceServerCredentialParamsInner
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {any}
     * @memberof CreateResourceServerCredentialParamsInner
     */
    resourceServerConfiguration: any | null;
}

/**
 * Check if a given object implements the CreateResourceServerCredentialParamsInner interface.
 */
export function instanceOfCreateResourceServerCredentialParamsInner(value: object): value is CreateResourceServerCredentialParamsInner {
    if (!('dataEncryptionKeyId' in value) || value['dataEncryptionKeyId'] === undefined) return false;
    if (!('resourceServerConfiguration' in value) || value['resourceServerConfiguration'] === undefined) return false;
    return true;
}

export function CreateResourceServerCredentialParamsInnerFromJSON(json: any): CreateResourceServerCredentialParamsInner {
    return CreateResourceServerCredentialParamsInnerFromJSONTyped(json, false);
}

export function CreateResourceServerCredentialParamsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResourceServerCredentialParamsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'dataEncryptionKeyId': json['data_encryption_key_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'resourceServerConfiguration': json['resource_server_configuration'],
    };
}

export function CreateResourceServerCredentialParamsInnerToJSON(json: any): CreateResourceServerCredentialParamsInner {
    return CreateResourceServerCredentialParamsInnerToJSONTyped(json, false);
}

export function CreateResourceServerCredentialParamsInnerToJSONTyped(value?: CreateResourceServerCredentialParamsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_encryption_key_id': value['dataEncryptionKeyId'],
        'metadata': value['metadata'],
        'resource_server_configuration': value['resourceServerConfiguration'],
    };
}

