/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSecretResponse
 */
export interface DeleteSecretResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSecretResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteSecretResponse interface.
 */
export function instanceOfDeleteSecretResponse(value: object): value is DeleteSecretResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteSecretResponseFromJSON(json: any): DeleteSecretResponse {
    return DeleteSecretResponseFromJSONTyped(json, false);
}

export function DeleteSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DeleteSecretResponseToJSON(json: any): DeleteSecretResponse {
    return DeleteSecretResponseToJSONTyped(json, false);
}

export function DeleteSecretResponseToJSONTyped(value?: DeleteSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

