/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response from deleting an API key
 * @export
 * @interface DeleteApiKeyResponse
 */
export interface DeleteApiKeyResponse {
	/**
	 * Whether the deletion was successful
	 * @type {boolean}
	 * @memberof DeleteApiKeyResponse
	 */
	success: boolean;
}

/**
 * Check if a given object implements the DeleteApiKeyResponse interface.
 */
export function instanceOfDeleteApiKeyResponse(
	value: object,
): value is DeleteApiKeyResponse {
	if (!("success" in value) || value.success === undefined) return false;
	return true;
}

export function DeleteApiKeyResponseFromJSON(json: any): DeleteApiKeyResponse {
	return DeleteApiKeyResponseFromJSONTyped(json, false);
}

export function DeleteApiKeyResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): DeleteApiKeyResponse {
	if (json == null) {
		return json;
	}
	return {
		success: json.success,
	};
}

export function DeleteApiKeyResponseToJSON(json: any): DeleteApiKeyResponse {
	return DeleteApiKeyResponseToJSONTyped(json, false);
}

export function DeleteApiKeyResponseToJSONTyped(
	value?: DeleteApiKeyResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		success: value.success,
	};
}
