/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncryptedOauthConfig } from "./EncryptedOauthConfig";
import {
	EncryptedOauthConfigFromJSON,
	EncryptedOauthConfigToJSON,
} from "./EncryptedOauthConfig";

/**
 *
 * @export
 * @interface EncryptedUserAuthFlowConfigOneOf1
 */
export interface EncryptedUserAuthFlowConfigOneOf1 {
	/**
	 *
	 * @type {EncryptedOauthConfig}
	 * @memberof EncryptedUserAuthFlowConfigOneOf1
	 */
	oauthAuthorizationCodeFlow: EncryptedOauthConfig;
}

/**
 * Check if a given object implements the EncryptedUserAuthFlowConfigOneOf1 interface.
 */
export function instanceOfEncryptedUserAuthFlowConfigOneOf1(
	value: object,
): value is EncryptedUserAuthFlowConfigOneOf1 {
	if (
		!("oauthAuthorizationCodeFlow" in value) ||
		value.oauthAuthorizationCodeFlow === undefined
	)
		return false;
	return true;
}

export function EncryptedUserAuthFlowConfigOneOf1FromJSON(
	json: any,
): EncryptedUserAuthFlowConfigOneOf1 {
	return EncryptedUserAuthFlowConfigOneOf1FromJSONTyped(json, false);
}

export function EncryptedUserAuthFlowConfigOneOf1FromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): EncryptedUserAuthFlowConfigOneOf1 {
	if (json == null) {
		return json;
	}
	return {
		oauthAuthorizationCodeFlow: EncryptedOauthConfigFromJSON(
			json.oauth_authorization_code_flow,
		),
	};
}

export function EncryptedUserAuthFlowConfigOneOf1ToJSON(
	json: any,
): EncryptedUserAuthFlowConfigOneOf1 {
	return EncryptedUserAuthFlowConfigOneOf1ToJSONTyped(json, false);
}

export function EncryptedUserAuthFlowConfigOneOf1ToJSONTyped(
	value?: EncryptedUserAuthFlowConfigOneOf1 | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		oauth_authorization_code_flow: EncryptedOauthConfigToJSON(
			value.oauthAuthorizationCodeFlow,
		),
	};
}
