/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EnvelopeEncryptionKeyOneOf
 */
export interface EnvelopeEncryptionKeyOneOf {
	/**
	 *
	 * @type {string}
	 * @memberof EnvelopeEncryptionKeyOneOf
	 */
	arn: string;
	/**
	 *
	 * @type {string}
	 * @memberof EnvelopeEncryptionKeyOneOf
	 */
	region: string;
	/**
	 *
	 * @type {string}
	 * @memberof EnvelopeEncryptionKeyOneOf
	 */
	type: EnvelopeEncryptionKeyOneOfTypeEnum;
}

/**
 * @export
 */
export const EnvelopeEncryptionKeyOneOfTypeEnum = {
	AwsKms: "aws_kms",
} as const;
export type EnvelopeEncryptionKeyOneOfTypeEnum =
	(typeof EnvelopeEncryptionKeyOneOfTypeEnum)[keyof typeof EnvelopeEncryptionKeyOneOfTypeEnum];

/**
 * Check if a given object implements the EnvelopeEncryptionKeyOneOf interface.
 */
export function instanceOfEnvelopeEncryptionKeyOneOf(
	value: object,
): value is EnvelopeEncryptionKeyOneOf {
	if (!("arn" in value) || value.arn === undefined) return false;
	if (!("region" in value) || value.region === undefined) return false;
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function EnvelopeEncryptionKeyOneOfFromJSON(
	json: any,
): EnvelopeEncryptionKeyOneOf {
	return EnvelopeEncryptionKeyOneOfFromJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyOneOfFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): EnvelopeEncryptionKeyOneOf {
	if (json == null) {
		return json;
	}
	return {
		arn: json.arn,
		region: json.region,
		type: json.type,
	};
}

export function EnvelopeEncryptionKeyOneOfToJSON(
	json: any,
): EnvelopeEncryptionKeyOneOf {
	return EnvelopeEncryptionKeyOneOfToJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyOneOfToJSONTyped(
	value?: EnvelopeEncryptionKeyOneOf | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		arn: value.arn,
		region: value.region,
		type: value.type,
	};
}
