/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DekConfig } from './DekConfig';
import {
    DekConfigFromJSON,
    DekConfigFromJSONTyped,
    DekConfigToJSON,
    DekConfigToJSONTyped,
} from './DekConfig';

/**
 * 
 * @export
 * @interface EnvelopeKeyConfigOneOf1
 */
export interface EnvelopeKeyConfigOneOf1 {
    /**
     * 
     * @type {{ [key: string]: DekConfig; }}
     * @memberof EnvelopeKeyConfigOneOf1
     */
    deks?: { [key: string]: DekConfig; };
    /**
     * 
     * @type {string}
     * @memberof EnvelopeKeyConfigOneOf1
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof EnvelopeKeyConfigOneOf1
     */
    type: EnvelopeKeyConfigOneOf1TypeEnum;
}


/**
 * @export
 */
export const EnvelopeKeyConfigOneOf1TypeEnum = {
    Local: 'local'
} as const;
export type EnvelopeKeyConfigOneOf1TypeEnum = typeof EnvelopeKeyConfigOneOf1TypeEnum[keyof typeof EnvelopeKeyConfigOneOf1TypeEnum];


/**
 * Check if a given object implements the EnvelopeKeyConfigOneOf1 interface.
 */
export function instanceOfEnvelopeKeyConfigOneOf1(value: object): value is EnvelopeKeyConfigOneOf1 {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EnvelopeKeyConfigOneOf1FromJSON(json: any): EnvelopeKeyConfigOneOf1 {
    return EnvelopeKeyConfigOneOf1FromJSONTyped(json, false);
}

export function EnvelopeKeyConfigOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvelopeKeyConfigOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'deks': json['deks'] == null ? undefined : (mapValues(json['deks'], DekConfigFromJSON)),
        'fileName': json['file_name'],
        'type': json['type'],
    };
}

export function EnvelopeKeyConfigOneOf1ToJSON(json: any): EnvelopeKeyConfigOneOf1 {
    return EnvelopeKeyConfigOneOf1ToJSONTyped(json, false);
}

export function EnvelopeKeyConfigOneOf1ToJSONTyped(value?: EnvelopeKeyConfigOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deks': value['deks'] == null ? undefined : (mapValues(value['deks'], DekConfigToJSON)),
        'file_name': value['fileName'],
        'type': value['type'],
    };
}

