/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvelopeEncryptionKeyLocal
 */
export interface EnvelopeEncryptionKeyLocal {
    /**
     * 
     * @type {string}
     * @memberof EnvelopeEncryptionKeyLocal
     */
    fileName: string;
}

/**
 * Check if a given object implements the EnvelopeEncryptionKeyLocal interface.
 */
export function instanceOfEnvelopeEncryptionKeyLocal(value: object): value is EnvelopeEncryptionKeyLocal {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function EnvelopeEncryptionKeyLocalFromJSON(json: any): EnvelopeEncryptionKeyLocal {
    return EnvelopeEncryptionKeyLocalFromJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyLocalFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvelopeEncryptionKeyLocal {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['file_name'],
    };
}

export function EnvelopeEncryptionKeyLocalToJSON(json: any): EnvelopeEncryptionKeyLocal {
    return EnvelopeEncryptionKeyLocalToJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyLocalToJSONTyped(value?: EnvelopeEncryptionKeyLocal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['fileName'],
    };
}

