/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnvelopeEncryptionKeyOneOf } from './EnvelopeEncryptionKeyOneOf';
import {
    instanceOfEnvelopeEncryptionKeyOneOf,
    EnvelopeEncryptionKeyOneOfFromJSON,
    EnvelopeEncryptionKeyOneOfFromJSONTyped,
    EnvelopeEncryptionKeyOneOfToJSON,
} from './EnvelopeEncryptionKeyOneOf';
import type { EnvelopeEncryptionKeyOneOf1 } from './EnvelopeEncryptionKeyOneOf1';
import {
    instanceOfEnvelopeEncryptionKeyOneOf1,
    EnvelopeEncryptionKeyOneOf1FromJSON,
    EnvelopeEncryptionKeyOneOf1FromJSONTyped,
    EnvelopeEncryptionKeyOneOf1ToJSON,
} from './EnvelopeEncryptionKeyOneOf1';

/**
 * @type EnvelopeEncryptionKey
 * 
 * @export
 */
export type EnvelopeEncryptionKey = EnvelopeEncryptionKeyOneOf | EnvelopeEncryptionKeyOneOf1;

export function EnvelopeEncryptionKeyFromJSON(json: any): EnvelopeEncryptionKey {
    return EnvelopeEncryptionKeyFromJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvelopeEncryptionKey {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEnvelopeEncryptionKeyOneOf(json)) {
        return EnvelopeEncryptionKeyOneOfFromJSONTyped(json, true);
    }
    if (instanceOfEnvelopeEncryptionKeyOneOf1(json)) {
        return EnvelopeEncryptionKeyOneOf1FromJSONTyped(json, true);
    }
    return {} as any;
}

export function EnvelopeEncryptionKeyToJSON(json: any): any {
    return EnvelopeEncryptionKeyToJSONTyped(json, false);
}

export function EnvelopeEncryptionKeyToJSONTyped(value?: EnvelopeEncryptionKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEnvelopeEncryptionKeyOneOf(value)) {
        return EnvelopeEncryptionKeyOneOfToJSON(value as EnvelopeEncryptionKeyOneOf);
    }
    if (instanceOfEnvelopeEncryptionKeyOneOf1(value)) {
        return EnvelopeEncryptionKeyOneOf1ToJSON(value as EnvelopeEncryptionKeyOneOf1);
    }
    return {};
}

