/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DekConfig } from './DekConfig';
import {
    DekConfigFromJSON,
    DekConfigFromJSONTyped,
    DekConfigToJSON,
    DekConfigToJSONTyped,
} from './DekConfig';

/**
 * 
 * @export
 * @interface EnvelopeKeyConfigOneOf
 */
export interface EnvelopeKeyConfigOneOf {
    /**
     * 
     * @type {string}
     * @memberof EnvelopeKeyConfigOneOf
     */
    arn: string;
    /**
     * 
     * @type {{ [key: string]: DekConfig; }}
     * @memberof EnvelopeKeyConfigOneOf
     */
    deks?: { [key: string]: DekConfig; };
    /**
     * 
     * @type {string}
     * @memberof EnvelopeKeyConfigOneOf
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof EnvelopeKeyConfigOneOf
     */
    type: EnvelopeKeyConfigOneOfTypeEnum;
}


/**
 * @export
 */
export const EnvelopeKeyConfigOneOfTypeEnum = {
    AwsKms: 'aws_kms'
} as const;
export type EnvelopeKeyConfigOneOfTypeEnum = typeof EnvelopeKeyConfigOneOfTypeEnum[keyof typeof EnvelopeKeyConfigOneOfTypeEnum];


/**
 * Check if a given object implements the EnvelopeKeyConfigOneOf interface.
 */
export function instanceOfEnvelopeKeyConfigOneOf(value: object): value is EnvelopeKeyConfigOneOf {
    if (!('arn' in value) || value['arn'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EnvelopeKeyConfigOneOfFromJSON(json: any): EnvelopeKeyConfigOneOf {
    return EnvelopeKeyConfigOneOfFromJSONTyped(json, false);
}

export function EnvelopeKeyConfigOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvelopeKeyConfigOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'arn': json['arn'],
        'deks': json['deks'] == null ? undefined : (mapValues(json['deks'], DekConfigFromJSON)),
        'region': json['region'],
        'type': json['type'],
    };
}

export function EnvelopeKeyConfigOneOfToJSON(json: any): EnvelopeKeyConfigOneOf {
    return EnvelopeKeyConfigOneOfToJSONTyped(json, false);
}

export function EnvelopeKeyConfigOneOfToJSONTyped(value?: EnvelopeKeyConfigOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arn': value['arn'],
        'deks': value['deks'] == null ? undefined : (mapValues(value['deks'], DekConfigToJSON)),
        'region': value['region'],
        'type': value['type'],
    };
}

