/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EnvironmentVariable
 */
export interface EnvironmentVariable {
	/**
	 *
	 * @type {Date}
	 * @memberof EnvironmentVariable
	 */
	createdAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof EnvironmentVariable
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof EnvironmentVariable
	 */
	key: string;
	/**
	 *
	 * @type {Date}
	 * @memberof EnvironmentVariable
	 */
	updatedAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof EnvironmentVariable
	 */
	value: string;
}

/**
 * Check if a given object implements the EnvironmentVariable interface.
 */
export function instanceOfEnvironmentVariable(
	value: object,
): value is EnvironmentVariable {
	if (!("createdAt" in value) || value.createdAt === undefined) return false;
	if (!("id" in value) || value.id === undefined) return false;
	if (!("key" in value) || value.key === undefined) return false;
	if (!("updatedAt" in value) || value.updatedAt === undefined) return false;
	if (!("value" in value) || value.value === undefined) return false;
	return true;
}

export function EnvironmentVariableFromJSON(json: any): EnvironmentVariable {
	return EnvironmentVariableFromJSONTyped(json, false);
}

export function EnvironmentVariableFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): EnvironmentVariable {
	if (json == null) {
		return json;
	}
	return {
		createdAt: new Date(json.created_at),
		id: json.id,
		key: json.key,
		updatedAt: new Date(json.updated_at),
		value: json.value,
	};
}

export function EnvironmentVariableToJSON(json: any): EnvironmentVariable {
	return EnvironmentVariableToJSONTyped(json, false);
}

export function EnvironmentVariableToJSONTyped(
	value?: EnvironmentVariable | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value.createdAt.toISOString(),
		id: value.id,
		key: value.key,
		updated_at: value.updatedAt.toISOString(),
		value: value.value,
	};
}
