/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FunctionInstanceConfig } from './FunctionInstanceConfig';
import {
    FunctionInstanceConfigFromJSON,
    FunctionInstanceConfigFromJSONTyped,
    FunctionInstanceConfigToJSON,
    FunctionInstanceConfigToJSONTyped,
} from './FunctionInstanceConfig';

/**
 * 
 * @export
 * @interface FunctionInstanceConfigPaginatedResponse
 */
export interface FunctionInstanceConfigPaginatedResponse {
    /**
     * 
     * @type {Array<FunctionInstanceConfig>}
     * @memberof FunctionInstanceConfigPaginatedResponse
     */
    items: Array<FunctionInstanceConfig>;
    /**
     * 
     * @type {string}
     * @memberof FunctionInstanceConfigPaginatedResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the FunctionInstanceConfigPaginatedResponse interface.
 */
export function instanceOfFunctionInstanceConfigPaginatedResponse(value: object): value is FunctionInstanceConfigPaginatedResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function FunctionInstanceConfigPaginatedResponseFromJSON(json: any): FunctionInstanceConfigPaginatedResponse {
    return FunctionInstanceConfigPaginatedResponseFromJSONTyped(json, false);
}

export function FunctionInstanceConfigPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FunctionInstanceConfigPaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FunctionInstanceConfigFromJSON)),
        'nextPageToken': json['next_page_token'] == null ? undefined : json['next_page_token'],
    };
}

export function FunctionInstanceConfigPaginatedResponseToJSON(json: any): FunctionInstanceConfigPaginatedResponse {
    return FunctionInstanceConfigPaginatedResponseToJSONTyped(json, false);
}

export function FunctionInstanceConfigPaginatedResponseToJSONTyped(value?: FunctionInstanceConfigPaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FunctionInstanceConfigToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

