/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GroupToRoleMapping } from "./GroupToRoleMapping";
import {
	GroupToRoleMappingFromJSON,
	GroupToRoleMappingToJSON,
} from "./GroupToRoleMapping";
import type { MappingSourceString } from "./MappingSourceString";
import {
	MappingSourceStringFromJSON,
	MappingSourceStringToJSON,
} from "./MappingSourceString";
import type { ScopeToGroupMapping } from "./ScopeToGroupMapping";
import {
	ScopeToGroupMappingFromJSON,
	ScopeToGroupMappingToJSON,
} from "./ScopeToGroupMapping";
import type { ScopeToRoleMapping } from "./ScopeToRoleMapping";
import {
	ScopeToRoleMappingFromJSON,
	ScopeToRoleMappingToJSON,
} from "./ScopeToRoleMapping";

/**
 *
 * @export
 * @interface JwtTokenMappingConfig
 */
export interface JwtTokenMappingConfig {
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	audienceField: MappingSourceString;
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	emailField?: MappingSourceString | null;
	/**
	 *
	 * @type {Array<GroupToRoleMapping>}
	 * @memberof JwtTokenMappingConfig
	 */
	groupToRoleMappings: Array<GroupToRoleMapping>;
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	groupsField?: MappingSourceString | null;
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	issuerField: MappingSourceString;
	/**
	 *
	 * @type {Array<ScopeToGroupMapping>}
	 * @memberof JwtTokenMappingConfig
	 */
	scopeToGroupMappings: Array<ScopeToGroupMapping>;
	/**
	 *
	 * @type {Array<ScopeToRoleMapping>}
	 * @memberof JwtTokenMappingConfig
	 */
	scopeToRoleMappings: Array<ScopeToRoleMapping>;
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	scopesField?: MappingSourceString | null;
	/**
	 *
	 * @type {MappingSourceString}
	 * @memberof JwtTokenMappingConfig
	 */
	subField: MappingSourceString;
}

/**
 * Check if a given object implements the JwtTokenMappingConfig interface.
 */
export function instanceOfJwtTokenMappingConfig(
	value: object,
): value is JwtTokenMappingConfig {
	if (!("audienceField" in value) || value.audienceField === undefined)
		return false;
	if (
		!("groupToRoleMappings" in value) ||
		value.groupToRoleMappings === undefined
	)
		return false;
	if (!("issuerField" in value) || value.issuerField === undefined)
		return false;
	if (
		!("scopeToGroupMappings" in value) ||
		value.scopeToGroupMappings === undefined
	)
		return false;
	if (
		!("scopeToRoleMappings" in value) ||
		value.scopeToRoleMappings === undefined
	)
		return false;
	if (!("subField" in value) || value.subField === undefined) return false;
	return true;
}

export function JwtTokenMappingConfigFromJSON(
	json: any,
): JwtTokenMappingConfig {
	return JwtTokenMappingConfigFromJSONTyped(json, false);
}

export function JwtTokenMappingConfigFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): JwtTokenMappingConfig {
	if (json == null) {
		return json;
	}
	return {
		audienceField: MappingSourceStringFromJSON(json.audience_field),
		emailField:
			json.email_field == null
				? undefined
				: MappingSourceStringFromJSON(json.email_field),
		groupToRoleMappings: (json.group_to_role_mappings as Array<any>).map(
			GroupToRoleMappingFromJSON,
		),
		groupsField:
			json.groups_field == null
				? undefined
				: MappingSourceStringFromJSON(json.groups_field),
		issuerField: MappingSourceStringFromJSON(json.issuer_field),
		scopeToGroupMappings: (json.scope_to_group_mappings as Array<any>).map(
			ScopeToGroupMappingFromJSON,
		),
		scopeToRoleMappings: (json.scope_to_role_mappings as Array<any>).map(
			ScopeToRoleMappingFromJSON,
		),
		scopesField:
			json.scopes_field == null
				? undefined
				: MappingSourceStringFromJSON(json.scopes_field),
		subField: MappingSourceStringFromJSON(json.sub_field),
	};
}

export function JwtTokenMappingConfigToJSON(json: any): JwtTokenMappingConfig {
	return JwtTokenMappingConfigToJSONTyped(json, false);
}

export function JwtTokenMappingConfigToJSONTyped(
	value?: JwtTokenMappingConfig | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		audience_field: MappingSourceStringToJSON(value.audienceField),
		email_field: MappingSourceStringToJSON(value.emailField),
		group_to_role_mappings: (value.groupToRoleMappings as Array<any>).map(
			GroupToRoleMappingToJSON,
		),
		groups_field: MappingSourceStringToJSON(value.groupsField),
		issuer_field: MappingSourceStringToJSON(value.issuerField),
		scope_to_group_mappings: (value.scopeToGroupMappings as Array<any>).map(
			ScopeToGroupMappingToJSON,
		),
		scope_to_role_mappings: (value.scopeToRoleMappings as Array<any>).map(
			ScopeToRoleMappingToJSON,
		),
		scopes_field: MappingSourceStringToJSON(value.scopesField),
		sub_field: MappingSourceStringToJSON(value.subField),
	};
}
