/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DecryptedSecret } from "./DecryptedSecret";
import {
	DecryptedSecretFromJSON,
	DecryptedSecretToJSON,
} from "./DecryptedSecret";

/**
 *
 * @export
 * @interface ListDecryptedSecretsResponse
 */
export interface ListDecryptedSecretsResponse {
	/**
	 *
	 * @type {string}
	 * @memberof ListDecryptedSecretsResponse
	 */
	nextPageToken?: string | null;
	/**
	 *
	 * @type {Array<DecryptedSecret>}
	 * @memberof ListDecryptedSecretsResponse
	 */
	secrets: Array<DecryptedSecret>;
}

/**
 * Check if a given object implements the ListDecryptedSecretsResponse interface.
 */
export function instanceOfListDecryptedSecretsResponse(
	value: object,
): value is ListDecryptedSecretsResponse {
	if (!("secrets" in value) || value.secrets === undefined) return false;
	return true;
}

export function ListDecryptedSecretsResponseFromJSON(
	json: any,
): ListDecryptedSecretsResponse {
	return ListDecryptedSecretsResponseFromJSONTyped(json, false);
}

export function ListDecryptedSecretsResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ListDecryptedSecretsResponse {
	if (json == null) {
		return json;
	}
	return {
		nextPageToken:
			json.next_page_token == null ? undefined : json.next_page_token,
		secrets: (json.secrets as Array<any>).map(DecryptedSecretFromJSON),
	};
}

export function ListDecryptedSecretsResponseToJSON(
	json: any,
): ListDecryptedSecretsResponse {
	return ListDecryptedSecretsResponseToJSONTyped(json, false);
}

export function ListDecryptedSecretsResponseToJSONTyped(
	value?: ListDecryptedSecretsResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		next_page_token: value.nextPageToken,
		secrets: (value.secrets as Array<any>).map(DecryptedSecretToJSON),
	};
}
