/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GetUserAuthFlowConfigResponse } from "./GetUserAuthFlowConfigResponse";
import {
	GetUserAuthFlowConfigResponseFromJSON,
	GetUserAuthFlowConfigResponseToJSON,
} from "./GetUserAuthFlowConfigResponse";

/**
 * Response from listing user auth flow configurations
 * @export
 * @interface ListUserAuthFlowConfigResponse
 */
export interface ListUserAuthFlowConfigResponse {
	/**
	 * The configurations
	 * @type {Array<GetUserAuthFlowConfigResponse>}
	 * @memberof ListUserAuthFlowConfigResponse
	 */
	items: Array<GetUserAuthFlowConfigResponse>;
	/**
	 * Token for the next page, if any
	 * @type {string}
	 * @memberof ListUserAuthFlowConfigResponse
	 */
	nextPageToken?: string | null;
}

/**
 * Check if a given object implements the ListUserAuthFlowConfigResponse interface.
 */
export function instanceOfListUserAuthFlowConfigResponse(
	value: object,
): value is ListUserAuthFlowConfigResponse {
	if (!("items" in value) || value.items === undefined) return false;
	return true;
}

export function ListUserAuthFlowConfigResponseFromJSON(
	json: any,
): ListUserAuthFlowConfigResponse {
	return ListUserAuthFlowConfigResponseFromJSONTyped(json, false);
}

export function ListUserAuthFlowConfigResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ListUserAuthFlowConfigResponse {
	if (json == null) {
		return json;
	}
	return {
		items: (json.items as Array<any>).map(
			GetUserAuthFlowConfigResponseFromJSON,
		),
		nextPageToken:
			json.next_page_token == null ? undefined : json.next_page_token,
	};
}

export function ListUserAuthFlowConfigResponseToJSON(
	json: any,
): ListUserAuthFlowConfigResponse {
	return ListUserAuthFlowConfigResponseToJSONTyped(json, false);
}

export function ListUserAuthFlowConfigResponseToJSONTyped(
	value?: ListUserAuthFlowConfigResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		items: (value.items as Array<any>).map(GetUserAuthFlowConfigResponseToJSON),
		next_page_token: value.nextPageToken,
	};
}
