/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { McpServerInstanceFunctionSerialized } from "./McpServerInstanceFunctionSerialized";
import {
	McpServerInstanceFunctionSerializedFromJSON,
	McpServerInstanceFunctionSerializedToJSON,
} from "./McpServerInstanceFunctionSerialized";

/**
 * Represents an MCP server instance with its associated functions
 * @export
 * @interface McpServerInstanceSerializedWithFunctions
 */
export interface McpServerInstanceSerializedWithFunctions {
	/**
	 *
	 * @type {Date}
	 * @memberof McpServerInstanceSerializedWithFunctions
	 */
	createdAt: Date;
	/**
	 *
	 * @type {Array<McpServerInstanceFunctionSerialized>}
	 * @memberof McpServerInstanceSerializedWithFunctions
	 */
	functions: Array<McpServerInstanceFunctionSerialized>;
	/**
	 *
	 * @type {string}
	 * @memberof McpServerInstanceSerializedWithFunctions
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof McpServerInstanceSerializedWithFunctions
	 */
	name: string;
	/**
	 *
	 * @type {Date}
	 * @memberof McpServerInstanceSerializedWithFunctions
	 */
	updatedAt: Date;
}

/**
 * Check if a given object implements the McpServerInstanceSerializedWithFunctions interface.
 */
export function instanceOfMcpServerInstanceSerializedWithFunctions(
	value: object,
): value is McpServerInstanceSerializedWithFunctions {
	if (!("createdAt" in value) || value.createdAt === undefined) return false;
	if (!("functions" in value) || value.functions === undefined) return false;
	if (!("id" in value) || value.id === undefined) return false;
	if (!("name" in value) || value.name === undefined) return false;
	if (!("updatedAt" in value) || value.updatedAt === undefined) return false;
	return true;
}

export function McpServerInstanceSerializedWithFunctionsFromJSON(
	json: any,
): McpServerInstanceSerializedWithFunctions {
	return McpServerInstanceSerializedWithFunctionsFromJSONTyped(json, false);
}

export function McpServerInstanceSerializedWithFunctionsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): McpServerInstanceSerializedWithFunctions {
	if (json == null) {
		return json;
	}
	return {
		createdAt: new Date(json.created_at),
		functions: (json.functions as Array<any>).map(
			McpServerInstanceFunctionSerializedFromJSON,
		),
		id: json.id,
		name: json.name,
		updatedAt: new Date(json.updated_at),
	};
}

export function McpServerInstanceSerializedWithFunctionsToJSON(
	json: any,
): McpServerInstanceSerializedWithFunctions {
	return McpServerInstanceSerializedWithFunctionsToJSONTyped(json, false);
}

export function McpServerInstanceSerializedWithFunctionsToJSONTyped(
	value?: McpServerInstanceSerializedWithFunctions | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value.createdAt.toISOString(),
		functions: (value.functions as Array<any>).map(
			McpServerInstanceFunctionSerializedToJSON,
		),
		id: value.id,
		name: value.name,
		updated_at: value.updatedAt.toISOString(),
	};
}
