/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MessagePart
 */
export interface MessagePart {
	/**
	 *
	 * @type {{ [key: string]: any; }}
	 * @memberof MessagePart
	 */
	metadata: { [key: string]: any };
	/**
	 *
	 * @type {string}
	 * @memberof MessagePart
	 */
	text: string;
	/**
	 *
	 * @type {string}
	 * @memberof MessagePart
	 */
	type: MessagePartTypeEnum;
}

/**
 * @export
 */
export const MessagePartTypeEnum = {
	TextPart: "text-part",
} as const;
export type MessagePartTypeEnum =
	(typeof MessagePartTypeEnum)[keyof typeof MessagePartTypeEnum];

/**
 * Check if a given object implements the MessagePart interface.
 */
export function instanceOfMessagePart(value: object): value is MessagePart {
	if (!("metadata" in value) || value.metadata === undefined) return false;
	if (!("text" in value) || value.text === undefined) return false;
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function MessagePartFromJSON(json: any): MessagePart {
	return MessagePartFromJSONTyped(json, false);
}

export function MessagePartFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): MessagePart {
	if (json == null) {
		return json;
	}
	return {
		metadata: json.metadata,
		text: json.text,
		type: json.type,
	};
}

export function MessagePartToJSON(json: any): MessagePart {
	return MessagePartToJSONTyped(json, false);
}

export function MessagePartToJSONTyped(
	value?: MessagePart | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		metadata: value.metadata,
		text: value.text,
		type: value.type,
	};
}
