/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Message } from "./Message";
import { MessageFromJSON, MessageToJSON } from "./Message";

/**
 *
 * @export
 * @interface MessageTaskTimelineItem
 */
export interface MessageTaskTimelineItem {
	/**
	 *
	 * @type {Message}
	 * @memberof MessageTaskTimelineItem
	 */
	message: Message;
}

/**
 * Check if a given object implements the MessageTaskTimelineItem interface.
 */
export function instanceOfMessageTaskTimelineItem(
	value: object,
): value is MessageTaskTimelineItem {
	if (!("message" in value) || value.message === undefined) return false;
	return true;
}

export function MessageTaskTimelineItemFromJSON(
	json: any,
): MessageTaskTimelineItem {
	return MessageTaskTimelineItemFromJSONTyped(json, false);
}

export function MessageTaskTimelineItemFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): MessageTaskTimelineItem {
	if (json == null) {
		return json;
	}
	return {
		message: MessageFromJSON(json.message),
	};
}

export function MessageTaskTimelineItemToJSON(
	json: any,
): MessageTaskTimelineItem {
	return MessageTaskTimelineItemToJSONTyped(json, false);
}

export function MessageTaskTimelineItemToJSONTyped(
	value?: MessageTaskTimelineItem | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		message: MessageToJSON(value.message),
	};
}
