/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MigrateDataEncryptionKeyParamsRoute
 */
export interface MigrateDataEncryptionKeyParamsRoute {
	/**
	 *
	 * @type {string}
	 * @memberof MigrateDataEncryptionKeyParamsRoute
	 */
	toEnvelopeEncryptionKeyId: string;
}

/**
 * Check if a given object implements the MigrateDataEncryptionKeyParamsRoute interface.
 */
export function instanceOfMigrateDataEncryptionKeyParamsRoute(
	value: object,
): value is MigrateDataEncryptionKeyParamsRoute {
	if (
		!("toEnvelopeEncryptionKeyId" in value) ||
		value.toEnvelopeEncryptionKeyId === undefined
	)
		return false;
	return true;
}

export function MigrateDataEncryptionKeyParamsRouteFromJSON(
	json: any,
): MigrateDataEncryptionKeyParamsRoute {
	return MigrateDataEncryptionKeyParamsRouteFromJSONTyped(json, false);
}

export function MigrateDataEncryptionKeyParamsRouteFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): MigrateDataEncryptionKeyParamsRoute {
	if (json == null) {
		return json;
	}
	return {
		toEnvelopeEncryptionKeyId: json.to_envelope_encryption_key_id,
	};
}

export function MigrateDataEncryptionKeyParamsRouteToJSON(
	json: any,
): MigrateDataEncryptionKeyParamsRoute {
	return MigrateDataEncryptionKeyParamsRouteToJSONTyped(json, false);
}

export function MigrateDataEncryptionKeyParamsRouteToJSONTyped(
	value?: MigrateDataEncryptionKeyParamsRoute | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		to_envelope_encryption_key_id: value.toEnvelopeEncryptionKeyId,
	};
}
