/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OauthConfig } from "./OauthConfig";
import { OauthConfigFromJSON, OauthConfigToJSON } from "./OauthConfig";
import type { TokenMapping } from "./TokenMapping";
import { TokenMappingFromJSON, TokenMappingToJSON } from "./TokenMapping";

/**
 * OIDC configuration extending OAuth2 with discovery and ID token support
 * @export
 * @interface OidcConfig
 */
export interface OidcConfig {
	/**
	 *
	 * @type {OauthConfig}
	 * @memberof OidcConfig
	 */
	baseConfig: OauthConfig;
	/**
	 *
	 * @type {string}
	 * @memberof OidcConfig
	 */
	discoveryEndpoint?: string | null;
	/**
	 *
	 * @type {string}
	 * @memberof OidcConfig
	 */
	id: string;
	/**
	 *
	 * @type {TokenMapping}
	 * @memberof OidcConfig
	 */
	mapping: TokenMapping;
}

/**
 * Check if a given object implements the OidcConfig interface.
 */
export function instanceOfOidcConfig(value: object): value is OidcConfig {
	if (!("baseConfig" in value) || value.baseConfig === undefined) return false;
	if (!("id" in value) || value.id === undefined) return false;
	if (!("mapping" in value) || value.mapping === undefined) return false;
	return true;
}

export function OidcConfigFromJSON(json: any): OidcConfig {
	return OidcConfigFromJSONTyped(json, false);
}

export function OidcConfigFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): OidcConfig {
	if (json == null) {
		return json;
	}
	return {
		baseConfig: OauthConfigFromJSON(json.base_config),
		discoveryEndpoint:
			json.discovery_endpoint == null ? undefined : json.discovery_endpoint,
		id: json.id,
		mapping: TokenMappingFromJSON(json.mapping),
	};
}

export function OidcConfigToJSON(json: any): OidcConfig {
	return OidcConfigToJSONTyped(json, false);
}

export function OidcConfigToJSONTyped(
	value?: OidcConfig | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		base_config: OauthConfigToJSON(value.baseConfig),
		discovery_endpoint: value.discoveryEndpoint,
		id: value.id,
		mapping: TokenMappingToJSON(value.mapping),
	};
}
