/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CredentialConfig } from "./CredentialConfig";
import {
	CredentialConfigFromJSON,
	CredentialConfigToJSON,
} from "./CredentialConfig";

/**
 *
 * @export
 * @interface ProviderConfig
 */
export interface ProviderConfig {
	/**
	 *
	 * @type {string}
	 * @memberof ProviderConfig
	 */
	credentialControllerTypeId: string;
	/**
	 *
	 * @type {string}
	 * @memberof ProviderConfig
	 */
	displayName: string;
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ProviderConfig
	 */
	functions?: Array<string> | null;
	/**
	 *
	 * @type {string}
	 * @memberof ProviderConfig
	 */
	providerControllerTypeId: string;
	/**
	 *
	 * @type {CredentialConfig}
	 * @memberof ProviderConfig
	 */
	resourceServerCredential: CredentialConfig;
	/**
	 *
	 * @type {CredentialConfig}
	 * @memberof ProviderConfig
	 */
	userCredential?: CredentialConfig | null;
}

/**
 * Check if a given object implements the ProviderConfig interface.
 */
export function instanceOfProviderConfig(
	value: object,
): value is ProviderConfig {
	if (
		!("credentialControllerTypeId" in value) ||
		value.credentialControllerTypeId === undefined
	)
		return false;
	if (!("displayName" in value) || value.displayName === undefined)
		return false;
	if (
		!("providerControllerTypeId" in value) ||
		value.providerControllerTypeId === undefined
	)
		return false;
	if (
		!("resourceServerCredential" in value) ||
		value.resourceServerCredential === undefined
	)
		return false;
	return true;
}

export function ProviderConfigFromJSON(json: any): ProviderConfig {
	return ProviderConfigFromJSONTyped(json, false);
}

export function ProviderConfigFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ProviderConfig {
	if (json == null) {
		return json;
	}
	return {
		credentialControllerTypeId: json.credential_controller_type_id,
		displayName: json.display_name,
		functions: json.functions == null ? undefined : json.functions,
		providerControllerTypeId: json.provider_controller_type_id,
		resourceServerCredential: CredentialConfigFromJSON(
			json.resource_server_credential,
		),
		userCredential:
			json.user_credential == null
				? undefined
				: CredentialConfigFromJSON(json.user_credential),
	};
}

export function ProviderConfigToJSON(json: any): ProviderConfig {
	return ProviderConfigToJSONTyped(json, false);
}

export function ProviderConfigToJSONTyped(
	value?: ProviderConfig | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		credential_controller_type_id: value.credentialControllerTypeId,
		display_name: value.displayName,
		functions: value.functions,
		provider_controller_type_id: value.providerControllerTypeId,
		resource_server_credential: CredentialConfigToJSON(
			value.resourceServerCredential,
		),
		user_credential: CredentialConfigToJSON(value.userCredential),
	};
}
