/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProviderControllerSerialized } from "./ProviderControllerSerialized";
import {
	ProviderControllerSerializedFromJSON,
	ProviderControllerSerializedToJSON,
} from "./ProviderControllerSerialized";

/**
 *
 * @export
 * @interface ProviderControllerSerializedPaginatedResponse
 */
export interface ProviderControllerSerializedPaginatedResponse {
	/**
	 *
	 * @type {Array<ProviderControllerSerialized>}
	 * @memberof ProviderControllerSerializedPaginatedResponse
	 */
	items: Array<ProviderControllerSerialized>;
	/**
	 *
	 * @type {string}
	 * @memberof ProviderControllerSerializedPaginatedResponse
	 */
	nextPageToken: string;
}

/**
 * Check if a given object implements the ProviderControllerSerializedPaginatedResponse interface.
 */
export function instanceOfProviderControllerSerializedPaginatedResponse(
	value: object,
): value is ProviderControllerSerializedPaginatedResponse {
	if (!("items" in value) || value.items === undefined) return false;
	if (!("nextPageToken" in value) || value.nextPageToken === undefined)
		return false;
	return true;
}

export function ProviderControllerSerializedPaginatedResponseFromJSON(
	json: any,
): ProviderControllerSerializedPaginatedResponse {
	return ProviderControllerSerializedPaginatedResponseFromJSONTyped(
		json,
		false,
	);
}

export function ProviderControllerSerializedPaginatedResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ProviderControllerSerializedPaginatedResponse {
	if (json == null) {
		return json;
	}
	return {
		items: (json.items as Array<any>).map(ProviderControllerSerializedFromJSON),
		nextPageToken: json.next_page_token,
	};
}

export function ProviderControllerSerializedPaginatedResponseToJSON(
	json: any,
): ProviderControllerSerializedPaginatedResponse {
	return ProviderControllerSerializedPaginatedResponseToJSONTyped(json, false);
}

export function ProviderControllerSerializedPaginatedResponseToJSONTyped(
	value?: ProviderControllerSerializedPaginatedResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		items: (value.items as Array<any>).map(ProviderControllerSerializedToJSON),
		next_page_token: value.nextPageToken,
	};
}
