/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ScimEmail } from "./ScimEmail";
import { ScimEmailFromJSON, ScimEmailToJSON } from "./ScimEmail";
import type { ScimMeta } from "./ScimMeta";
import { ScimMetaFromJSON, ScimMetaToJSON } from "./ScimMeta";
import type { ScimName } from "./ScimName";
import { ScimNameFromJSON, ScimNameToJSON } from "./ScimName";
import type { ScimUserGroup } from "./ScimUserGroup";
import { ScimUserGroupFromJSON, ScimUserGroupToJSON } from "./ScimUserGroup";

/**
 * SCIM 2.0 User resource
 * @export
 * @interface ScimUser
 */
export interface ScimUser {
	/**
	 * Whether the user is active
	 * @type {boolean}
	 * @memberof ScimUser
	 */
	active?: boolean;
	/**
	 * Display name
	 * @type {string}
	 * @memberof ScimUser
	 */
	displayName?: string | null;
	/**
	 * Email addresses
	 * @type {Array<ScimEmail>}
	 * @memberof ScimUser
	 */
	emails?: Array<ScimEmail>;
	/**
	 * External identifier from the IDP
	 * @type {string}
	 * @memberof ScimUser
	 */
	externalId?: string | null;
	/**
	 * Groups the user belongs to (read-only)
	 * @type {Array<ScimUserGroup>}
	 * @memberof ScimUser
	 */
	groups?: Array<ScimUserGroup>;
	/**
	 * Unique identifier (our internal ID)
	 * @type {string}
	 * @memberof ScimUser
	 */
	id?: string | null;
	/**
	 * Resource metadata
	 * @type {ScimMeta}
	 * @memberof ScimUser
	 */
	meta?: ScimMeta | null;
	/**
	 * User's name components
	 * @type {ScimName}
	 * @memberof ScimUser
	 */
	name?: ScimName | null;
	/**
	 * SCIM schema URIs
	 * @type {Array<string>}
	 * @memberof ScimUser
	 */
	schemas?: Array<string>;
	/**
	 * Username (unique identifier for the user)
	 * @type {string}
	 * @memberof ScimUser
	 */
	userName: string;
}

/**
 * Check if a given object implements the ScimUser interface.
 */
export function instanceOfScimUser(value: object): value is ScimUser {
	if (!("userName" in value) || value.userName === undefined) return false;
	return true;
}

export function ScimUserFromJSON(json: any): ScimUser {
	return ScimUserFromJSONTyped(json, false);
}

export function ScimUserFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ScimUser {
	if (json == null) {
		return json;
	}
	return {
		active: json.active == null ? undefined : json.active,
		displayName: json.displayName == null ? undefined : json.displayName,
		emails:
			json.emails == null
				? undefined
				: (json.emails as Array<any>).map(ScimEmailFromJSON),
		externalId: json.externalId == null ? undefined : json.externalId,
		groups:
			json.groups == null
				? undefined
				: (json.groups as Array<any>).map(ScimUserGroupFromJSON),
		id: json.id == null ? undefined : json.id,
		meta: json.meta == null ? undefined : ScimMetaFromJSON(json.meta),
		name: json.name == null ? undefined : ScimNameFromJSON(json.name),
		schemas: json.schemas == null ? undefined : json.schemas,
		userName: json.userName,
	};
}

export function ScimUserToJSON(json: any): ScimUser {
	return ScimUserToJSONTyped(json, false);
}

export function ScimUserToJSONTyped(
	value?: ScimUser | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		active: value.active,
		displayName: value.displayName,
		emails:
			value.emails == null
				? undefined
				: (value.emails as Array<any>).map(ScimEmailToJSON),
		externalId: value.externalId,
		groups:
			value.groups == null
				? undefined
				: (value.groups as Array<any>).map(ScimUserGroupToJSON),
		id: value.id,
		meta: ScimMetaToJSON(value.meta),
		name: ScimNameToJSON(value.name),
		schemas: value.schemas,
		userName: value.userName,
	};
}
