/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ScimPatchOp } from "./ScimPatchOp";
import { ScimPatchOpFromJSON, ScimPatchOpToJSON } from "./ScimPatchOp";

/**
 * SCIM 2.0 PATCH operation
 * @export
 * @interface ScimPatchOperation
 */
export interface ScimPatchOperation {
	/**
	 *
	 * @type {ScimPatchOp}
	 * @memberof ScimPatchOperation
	 */
	op: ScimPatchOp;
	/**
	 *
	 * @type {string}
	 * @memberof ScimPatchOperation
	 */
	path?: string | null;
	/**
	 *
	 * @type {any}
	 * @memberof ScimPatchOperation
	 */
	value?: any | null;
}

/**
 * Check if a given object implements the ScimPatchOperation interface.
 */
export function instanceOfScimPatchOperation(
	value: object,
): value is ScimPatchOperation {
	if (!("op" in value) || value.op === undefined) return false;
	return true;
}

export function ScimPatchOperationFromJSON(json: any): ScimPatchOperation {
	return ScimPatchOperationFromJSONTyped(json, false);
}

export function ScimPatchOperationFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ScimPatchOperation {
	if (json == null) {
		return json;
	}
	return {
		op: ScimPatchOpFromJSON(json.op),
		path: json.path == null ? undefined : json.path,
		value: json.value == null ? undefined : json.value,
	};
}

export function ScimPatchOperationToJSON(json: any): ScimPatchOperation {
	return ScimPatchOperationToJSONTyped(json, false);
}

export function ScimPatchOperationToJSONTyped(
	value?: ScimPatchOperation | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		op: ScimPatchOpToJSON(value.op),
		path: value.path,
		value: value.value,
	};
}
