/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SCIM 2.0 PATCH operation type
 * @export
 */
export const ScimPatchOp = {
	Add: "add",
	Remove: "remove",
	Replace: "replace",
} as const;
export type ScimPatchOp = (typeof ScimPatchOp)[keyof typeof ScimPatchOp];

export function instanceOfScimPatchOp(value: any): boolean {
	for (const key in ScimPatchOp) {
		if (Object.hasOwn(ScimPatchOp, key)) {
			if (ScimPatchOp[key as keyof typeof ScimPatchOp] === value) {
				return true;
			}
		}
	}
	return false;
}

export function ScimPatchOpFromJSON(json: any): ScimPatchOp {
	return ScimPatchOpFromJSONTyped(json, false);
}

export function ScimPatchOpFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ScimPatchOp {
	return json as ScimPatchOp;
}

export function ScimPatchOpToJSON(value?: ScimPatchOp | null): any {
	return value as any;
}

export function ScimPatchOpToJSONTyped(
	value: any,
	_ignoreDiscriminator: boolean,
): ScimPatchOp {
	return value as ScimPatchOp;
}
