/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScopeToGroupMapping
 */
export interface ScopeToGroupMapping {
	/**
	 *
	 * @type {string}
	 * @memberof ScopeToGroupMapping
	 */
	group: string;
	/**
	 *
	 * @type {string}
	 * @memberof ScopeToGroupMapping
	 */
	scope: string;
}

/**
 * Check if a given object implements the ScopeToGroupMapping interface.
 */
export function instanceOfScopeToGroupMapping(
	value: object,
): value is ScopeToGroupMapping {
	if (!("group" in value) || value.group === undefined) return false;
	if (!("scope" in value) || value.scope === undefined) return false;
	return true;
}

export function ScopeToGroupMappingFromJSON(json: any): ScopeToGroupMapping {
	return ScopeToGroupMappingFromJSONTyped(json, false);
}

export function ScopeToGroupMappingFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ScopeToGroupMapping {
	if (json == null) {
		return json;
	}
	return {
		group: json.group,
		scope: json.scope,
	};
}

export function ScopeToGroupMappingToJSON(json: any): ScopeToGroupMapping {
	return ScopeToGroupMappingToJSONTyped(json, false);
}

export function ScopeToGroupMappingToJSONTyped(
	value?: ScopeToGroupMapping | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		group: value.group,
		scope: value.scope,
	};
}
