/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Role } from "./Role";
import { RoleFromJSON, RoleToJSON } from "./Role";

/**
 *
 * @export
 * @interface ScopeToRoleMapping
 */
export interface ScopeToRoleMapping {
	/**
	 *
	 * @type {Role}
	 * @memberof ScopeToRoleMapping
	 */
	role: Role;
	/**
	 *
	 * @type {string}
	 * @memberof ScopeToRoleMapping
	 */
	scope: string;
}

/**
 * Check if a given object implements the ScopeToRoleMapping interface.
 */
export function instanceOfScopeToRoleMapping(
	value: object,
): value is ScopeToRoleMapping {
	if (!("role" in value) || value.role === undefined) return false;
	if (!("scope" in value) || value.scope === undefined) return false;
	return true;
}

export function ScopeToRoleMappingFromJSON(json: any): ScopeToRoleMapping {
	return ScopeToRoleMappingFromJSONTyped(json, false);
}

export function ScopeToRoleMappingFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ScopeToRoleMapping {
	if (json == null) {
		return json;
	}
	return {
		role: RoleFromJSON(json.role),
		scope: json.scope,
	};
}

export function ScopeToRoleMappingToJSON(json: any): ScopeToRoleMapping {
	return ScopeToRoleMappingToJSONTyped(json, false);
}

export function ScopeToRoleMappingToJSONTyped(
	value?: ScopeToRoleMapping | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		role: RoleToJSON(value.role),
		scope: value.scope,
	};
}
