/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Secret
 */
export interface Secret {
	/**
	 *
	 * @type {Date}
	 * @memberof Secret
	 */
	createdAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof Secret
	 */
	dekAlias: string;
	/**
	 *
	 * @type {string}
	 * @memberof Secret
	 */
	encryptedSecret: string;
	/**
	 *
	 * @type {string}
	 * @memberof Secret
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof Secret
	 */
	key: string;
	/**
	 *
	 * @type {Date}
	 * @memberof Secret
	 */
	updatedAt: Date;
}

/**
 * Check if a given object implements the Secret interface.
 */
export function instanceOfSecret(value: object): value is Secret {
	if (!("createdAt" in value) || value.createdAt === undefined) return false;
	if (!("dekAlias" in value) || value.dekAlias === undefined) return false;
	if (!("encryptedSecret" in value) || value.encryptedSecret === undefined)
		return false;
	if (!("id" in value) || value.id === undefined) return false;
	if (!("key" in value) || value.key === undefined) return false;
	if (!("updatedAt" in value) || value.updatedAt === undefined) return false;
	return true;
}

export function SecretFromJSON(json: any): Secret {
	return SecretFromJSONTyped(json, false);
}

export function SecretFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Secret {
	if (json == null) {
		return json;
	}
	return {
		createdAt: new Date(json.created_at),
		dekAlias: json.dek_alias,
		encryptedSecret: json.encrypted_secret,
		id: json.id,
		key: json.key,
		updatedAt: new Date(json.updated_at),
	};
}

export function SecretToJSON(json: any): Secret {
	return SecretToJSONTyped(json, false);
}

export function SecretToJSONTyped(
	value?: Secret | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value.createdAt.toISOString(),
		dek_alias: value.dekAlias,
		encrypted_secret: value.encryptedSecret,
		id: value.id,
		key: value.key,
		updated_at: value.updatedAt.toISOString(),
	};
}
