/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BridgeConfig } from "./BridgeConfig";
import { BridgeConfigFromJSON, BridgeConfigToJSON } from "./BridgeConfig";
import type { EncryptionConfig } from "./EncryptionConfig";
import {
	EncryptionConfigFromJSON,
	EncryptionConfigToJSON,
} from "./EncryptionConfig";
import type { SecretConfig } from "./SecretConfig";
import { SecretConfigFromJSON, SecretConfigToJSON } from "./SecretConfig";

/**
 *
 * @export
 * @interface SomaAgentDefinition
 */
export interface SomaAgentDefinition {
	/**
	 *
	 * @type {BridgeConfig}
	 * @memberof SomaAgentDefinition
	 */
	bridge?: BridgeConfig | null;
	/**
	 *
	 * @type {EncryptionConfig}
	 * @memberof SomaAgentDefinition
	 */
	encryption?: EncryptionConfig | null;
	/**
	 *
	 * @type {{ [key: string]: SecretConfig; }}
	 * @memberof SomaAgentDefinition
	 */
	secrets?: { [key: string]: SecretConfig };
}

/**
 * Check if a given object implements the SomaAgentDefinition interface.
 */
export function instanceOfSomaAgentDefinition(
	value: object,
): value is SomaAgentDefinition {
	return true;
}

export function SomaAgentDefinitionFromJSON(json: any): SomaAgentDefinition {
	return SomaAgentDefinitionFromJSONTyped(json, false);
}

export function SomaAgentDefinitionFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SomaAgentDefinition {
	if (json == null) {
		return json;
	}
	return {
		bridge: json.bridge == null ? undefined : BridgeConfigFromJSON(json.bridge),
		encryption:
			json.encryption == null
				? undefined
				: EncryptionConfigFromJSON(json.encryption),
		secrets:
			json.secrets == null
				? undefined
				: mapValues(json.secrets, SecretConfigFromJSON),
	};
}

export function SomaAgentDefinitionToJSON(json: any): SomaAgentDefinition {
	return SomaAgentDefinitionToJSONTyped(json, false);
}

export function SomaAgentDefinitionToJSONTyped(
	value?: SomaAgentDefinition | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		bridge: BridgeConfigToJSON(value.bridge),
		encryption: EncryptionConfigToJSON(value.encryption),
		secrets:
			value.secrets == null
				? undefined
				: mapValues(value.secrets, SecretConfigToJSON),
	};
}
