/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StsConfigYamlOneOf } from "./StsConfigYamlOneOf";
import {
	instanceOfStsConfigYamlOneOf,
	StsConfigYamlOneOfFromJSONTyped,
	StsConfigYamlOneOfToJSON,
} from "./StsConfigYamlOneOf";
import type { StsConfigYamlOneOf1 } from "./StsConfigYamlOneOf1";
import {
	instanceOfStsConfigYamlOneOf1,
	StsConfigYamlOneOf1FromJSONTyped,
	StsConfigYamlOneOf1ToJSON,
} from "./StsConfigYamlOneOf1";

/**
 * @type StsConfigYaml
 * STS configuration stored in soma.yaml
 * @export
 */
export type StsConfigYaml = StsConfigYamlOneOf | StsConfigYamlOneOf1;

export function StsConfigYamlFromJSON(json: any): StsConfigYaml {
	return StsConfigYamlFromJSONTyped(json, false);
}

export function StsConfigYamlFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): StsConfigYaml {
	if (json == null) {
		return json;
	}
	if (typeof json !== "object") {
		return json;
	}
	if (instanceOfStsConfigYamlOneOf(json)) {
		return StsConfigYamlOneOfFromJSONTyped(json, true);
	}
	if (instanceOfStsConfigYamlOneOf1(json)) {
		return StsConfigYamlOneOf1FromJSONTyped(json, true);
	}

	return {} as any;
}

export function StsConfigYamlToJSON(json: any): any {
	return StsConfigYamlToJSONTyped(json, false);
}

export function StsConfigYamlToJSONTyped(
	value?: StsConfigYaml | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}
	if (typeof value !== "object") {
		return value;
	}
	if (instanceOfStsConfigYamlOneOf(value)) {
		return StsConfigYamlOneOfToJSON(value as StsConfigYamlOneOf);
	}
	if (instanceOfStsConfigYamlOneOf1(value)) {
		return StsConfigYamlOneOf1ToJSON(value as StsConfigYamlOneOf1);
	}

	return {};
}
