/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GroupToRoleMappingYaml } from "./GroupToRoleMappingYaml";
import {
	GroupToRoleMappingYamlFromJSON,
	GroupToRoleMappingYamlToJSON,
} from "./GroupToRoleMappingYaml";
import type { JwtMappingConfigYaml } from "./JwtMappingConfigYaml";
import {
	JwtMappingConfigYamlFromJSON,
	JwtMappingConfigYamlToJSON,
} from "./JwtMappingConfigYaml";
import type { JwtValidationConfigYaml } from "./JwtValidationConfigYaml";
import {
	JwtValidationConfigYamlFromJSON,
	JwtValidationConfigYamlToJSON,
} from "./JwtValidationConfigYaml";
import type { ScopeToGroupMappingYaml } from "./ScopeToGroupMappingYaml";
import {
	ScopeToGroupMappingYamlFromJSON,
	ScopeToGroupMappingYamlToJSON,
} from "./ScopeToGroupMappingYaml";
import type { ScopeToRoleMappingYaml } from "./ScopeToRoleMappingYaml";
import {
	ScopeToRoleMappingYamlFromJSON,
	ScopeToRoleMappingYamlToJSON,
} from "./ScopeToRoleMappingYaml";
import type { TokenLocationYaml } from "./TokenLocationYaml";
import {
	TokenLocationYamlFromJSON,
	TokenLocationYamlToJSON,
} from "./TokenLocationYaml";

/**
 * JWT template configuration for external IdPs
 * @export
 * @interface StsConfigYamlOneOf
 */
export interface StsConfigYamlOneOf {
	/**
	 * Group to role mappings
	 * @type {Array<GroupToRoleMappingYaml>}
	 * @memberof StsConfigYamlOneOf
	 */
	groupToRoleMappings?: Array<GroupToRoleMappingYaml>;
	/**
	 * JWKS URI to fetch public keys from
	 * @type {string}
	 * @memberof StsConfigYamlOneOf
	 */
	jwksUri: string;
	/**
	 * Field mapping from JWT claims to internal fields
	 * @type {JwtMappingConfigYaml}
	 * @memberof StsConfigYamlOneOf
	 */
	mapping: JwtMappingConfigYaml;
	/**
	 * Scope to group mappings (maps scopes to internal groups)
	 * @type {Array<ScopeToGroupMappingYaml>}
	 * @memberof StsConfigYamlOneOf
	 */
	scopeToGroupMappings?: Array<ScopeToGroupMappingYaml>;
	/**
	 * Scope to role mappings
	 * @type {Array<ScopeToRoleMappingYaml>}
	 * @memberof StsConfigYamlOneOf
	 */
	scopeToRoleMappings?: Array<ScopeToRoleMappingYaml>;
	/**
	 * Where to find the token in the request
	 * @type {TokenLocationYaml}
	 * @memberof StsConfigYamlOneOf
	 */
	tokenLocation: TokenLocationYaml;
	/**
	 * Validation rules
	 * @type {JwtValidationConfigYaml}
	 * @memberof StsConfigYamlOneOf
	 */
	validation: JwtValidationConfigYaml;
	/**
	 *
	 * @type {string}
	 * @memberof StsConfigYamlOneOf
	 */
	type: StsConfigYamlOneOfTypeEnum;
}

/**
 * @export
 */
export const StsConfigYamlOneOfTypeEnum = {
	JwtTemplate: "jwt_template",
} as const;
export type StsConfigYamlOneOfTypeEnum =
	(typeof StsConfigYamlOneOfTypeEnum)[keyof typeof StsConfigYamlOneOfTypeEnum];

/**
 * Check if a given object implements the StsConfigYamlOneOf interface.
 */
export function instanceOfStsConfigYamlOneOf(
	value: object,
): value is StsConfigYamlOneOf {
	if (!("jwksUri" in value) || value.jwksUri === undefined) return false;
	if (!("mapping" in value) || value.mapping === undefined) return false;
	if (!("tokenLocation" in value) || value.tokenLocation === undefined)
		return false;
	if (!("validation" in value) || value.validation === undefined) return false;
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function StsConfigYamlOneOfFromJSON(json: any): StsConfigYamlOneOf {
	return StsConfigYamlOneOfFromJSONTyped(json, false);
}

export function StsConfigYamlOneOfFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): StsConfigYamlOneOf {
	if (json == null) {
		return json;
	}
	return {
		groupToRoleMappings:
			json.group_to_role_mappings == null
				? undefined
				: (json.group_to_role_mappings as Array<any>).map(
						GroupToRoleMappingYamlFromJSON,
					),
		jwksUri: json.jwks_uri,
		mapping: JwtMappingConfigYamlFromJSON(json.mapping),
		scopeToGroupMappings:
			json.scope_to_group_mappings == null
				? undefined
				: (json.scope_to_group_mappings as Array<any>).map(
						ScopeToGroupMappingYamlFromJSON,
					),
		scopeToRoleMappings:
			json.scope_to_role_mappings == null
				? undefined
				: (json.scope_to_role_mappings as Array<any>).map(
						ScopeToRoleMappingYamlFromJSON,
					),
		tokenLocation: TokenLocationYamlFromJSON(json.token_location),
		validation: JwtValidationConfigYamlFromJSON(json.validation),
		type: json.type,
	};
}

export function StsConfigYamlOneOfToJSON(json: any): StsConfigYamlOneOf {
	return StsConfigYamlOneOfToJSONTyped(json, false);
}

export function StsConfigYamlOneOfToJSONTyped(
	value?: StsConfigYamlOneOf | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		group_to_role_mappings:
			value.groupToRoleMappings == null
				? undefined
				: (value.groupToRoleMappings as Array<any>).map(
						GroupToRoleMappingYamlToJSON,
					),
		jwks_uri: value.jwksUri,
		mapping: JwtMappingConfigYamlToJSON(value.mapping),
		scope_to_group_mappings:
			value.scopeToGroupMappings == null
				? undefined
				: (value.scopeToGroupMappings as Array<any>).map(
						ScopeToGroupMappingYamlToJSON,
					),
		scope_to_role_mappings:
			value.scopeToRoleMappings == null
				? undefined
				: (value.scopeToRoleMappings as Array<any>).map(
						ScopeToRoleMappingYamlToJSON,
					),
		token_location: TokenLocationYamlToJSON(value.tokenLocation),
		validation: JwtValidationConfigYamlToJSON(value.validation),
		type: value.type,
	};
}
