/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Dev mode configuration (allows any authentication in dev)
 * @export
 * @interface StsConfigYamlOneOf1
 */
export interface StsConfigYamlOneOf1 {
	/**
	 *
	 * @type {string}
	 * @memberof StsConfigYamlOneOf1
	 */
	type: StsConfigYamlOneOf1TypeEnum;
}

/**
 * @export
 */
export const StsConfigYamlOneOf1TypeEnum = {
	Dev: "dev",
} as const;
export type StsConfigYamlOneOf1TypeEnum =
	(typeof StsConfigYamlOneOf1TypeEnum)[keyof typeof StsConfigYamlOneOf1TypeEnum];

/**
 * Check if a given object implements the StsConfigYamlOneOf1 interface.
 */
export function instanceOfStsConfigYamlOneOf1(
	value: object,
): value is StsConfigYamlOneOf1 {
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function StsConfigYamlOneOf1FromJSON(json: any): StsConfigYamlOneOf1 {
	return StsConfigYamlOneOf1FromJSONTyped(json, false);
}

export function StsConfigYamlOneOf1FromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): StsConfigYamlOneOf1 {
	if (json == null) {
		return json;
	}
	return {
		type: json.type,
	};
}

export function StsConfigYamlOneOf1ToJSON(json: any): StsConfigYamlOneOf1 {
	return StsConfigYamlOneOf1ToJSONTyped(json, false);
}

export function StsConfigYamlOneOf1ToJSONTyped(
	value?: StsConfigYamlOneOf1 | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		type: value.type,
	};
}
