/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskStatus } from './TaskStatus';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
    TaskStatusToJSONTyped,
} from './TaskStatus';

/**
 * 
 * @export
 * @interface TaskStatusUpdateTaskTimelineItem
 */
export interface TaskStatusUpdateTaskTimelineItem {
    /**
     * 
     * @type {TaskStatus}
     * @memberof TaskStatusUpdateTaskTimelineItem
     */
    status: TaskStatus;
    /**
     * 
     * @type {string}
     * @memberof TaskStatusUpdateTaskTimelineItem
     */
    statusMessageId?: string;
}



/**
 * Check if a given object implements the TaskStatusUpdateTaskTimelineItem interface.
 */
export function instanceOfTaskStatusUpdateTaskTimelineItem(value: object): value is TaskStatusUpdateTaskTimelineItem {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TaskStatusUpdateTaskTimelineItemFromJSON(json: any): TaskStatusUpdateTaskTimelineItem {
    return TaskStatusUpdateTaskTimelineItemFromJSONTyped(json, false);
}

export function TaskStatusUpdateTaskTimelineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatusUpdateTaskTimelineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'status': TaskStatusFromJSON(json['status']),
        'statusMessageId': json['status_message_id'] == null ? undefined : json['status_message_id'],
    };
}

export function TaskStatusUpdateTaskTimelineItemToJSON(json: any): TaskStatusUpdateTaskTimelineItem {
    return TaskStatusUpdateTaskTimelineItemToJSONTyped(json, false);
}

export function TaskStatusUpdateTaskTimelineItemToJSONTyped(value?: TaskStatusUpdateTaskTimelineItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': TaskStatusToJSON(value['status']),
        'status_message_id': value['statusMessageId'],
    };
}

