/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Text part of a message
 * @export
 * @interface TextPart
 */
export interface TextPart {
	/**
	 *
	 * @type {{ [key: string]: any; }}
	 * @memberof TextPart
	 */
	metadata: { [key: string]: any };
	/**
	 *
	 * @type {string}
	 * @memberof TextPart
	 */
	text: string;
}

/**
 * Check if a given object implements the TextPart interface.
 */
export function instanceOfTextPart(value: object): value is TextPart {
	if (!("metadata" in value) || value.metadata === undefined) return false;
	if (!("text" in value) || value.text === undefined) return false;
	return true;
}

export function TextPartFromJSON(json: any): TextPart {
	return TextPartFromJSONTyped(json, false);
}

export function TextPartFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TextPart {
	if (json == null) {
		return json;
	}
	return {
		metadata: json.metadata,
		text: json.text,
	};
}

export function TextPartToJSON(json: any): TextPart {
	return TextPartToJSONTyped(json, false);
}

export function TextPartToJSONTyped(
	value?: TextPart | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		metadata: value.metadata,
		text: value.text,
	};
}
