/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TokenLocationOneOf1
 */
export interface TokenLocationOneOf1 {
	/**
	 *
	 * @type {string}
	 * @memberof TokenLocationOneOf1
	 */
	cookie: string;
}

/**
 * Check if a given object implements the TokenLocationOneOf1 interface.
 */
export function instanceOfTokenLocationOneOf1(
	value: object,
): value is TokenLocationOneOf1 {
	if (!("cookie" in value) || value.cookie === undefined) return false;
	return true;
}

export function TokenLocationOneOf1FromJSON(json: any): TokenLocationOneOf1 {
	return TokenLocationOneOf1FromJSONTyped(json, false);
}

export function TokenLocationOneOf1FromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TokenLocationOneOf1 {
	if (json == null) {
		return json;
	}
	return {
		cookie: json.Cookie,
	};
}

export function TokenLocationOneOf1ToJSON(json: any): TokenLocationOneOf1 {
	return TokenLocationOneOf1ToJSONTyped(json, false);
}

export function TokenLocationOneOf1ToJSONTyped(
	value?: TokenLocationOneOf1 | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		Cookie: value.cookie,
	};
}
