/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TokenLocationOneOf
 */
export interface TokenLocationOneOf {
	/**
	 *
	 * @type {string}
	 * @memberof TokenLocationOneOf
	 */
	header: string;
}

/**
 * Check if a given object implements the TokenLocationOneOf interface.
 */
export function instanceOfTokenLocationOneOf(
	value: object,
): value is TokenLocationOneOf {
	if (!("header" in value) || value.header === undefined) return false;
	return true;
}

export function TokenLocationOneOfFromJSON(json: any): TokenLocationOneOf {
	return TokenLocationOneOfFromJSONTyped(json, false);
}

export function TokenLocationOneOfFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TokenLocationOneOf {
	if (json == null) {
		return json;
	}
	return {
		header: json.Header,
	};
}

export function TokenLocationOneOfToJSON(json: any): TokenLocationOneOf {
	return TokenLocationOneOfToJSONTyped(json, false);
}

export function TokenLocationOneOfToJSONTyped(
	value?: TokenLocationOneOf | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		Header: value.header,
	};
}
