/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body for token exchange and refresh endpoints
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
	/**
	 * The access token
	 * @type {string}
	 * @memberof TokenResponse
	 */
	accessToken: string;
	/**
	 * Token expiration time in seconds
	 * @type {number}
	 * @memberof TokenResponse
	 */
	expiresIn: number;
	/**
	 * The refresh token (only present on exchange, not refresh)
	 * @type {string}
	 * @memberof TokenResponse
	 */
	refreshToken?: string | null;
	/**
	 * Token type (always "Bearer")
	 * @type {string}
	 * @memberof TokenResponse
	 */
	tokenType: string;
}

/**
 * Check if a given object implements the TokenResponse interface.
 */
export function instanceOfTokenResponse(value: object): value is TokenResponse {
	if (!("accessToken" in value) || value.accessToken === undefined)
		return false;
	if (!("expiresIn" in value) || value.expiresIn === undefined) return false;
	if (!("tokenType" in value) || value.tokenType === undefined) return false;
	return true;
}

export function TokenResponseFromJSON(json: any): TokenResponse {
	return TokenResponseFromJSONTyped(json, false);
}

export function TokenResponseFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TokenResponse {
	if (json == null) {
		return json;
	}
	return {
		accessToken: json.access_token,
		expiresIn: json.expires_in,
		refreshToken: json.refresh_token == null ? undefined : json.refresh_token,
		tokenType: json.token_type,
	};
}

export function TokenResponseToJSON(json: any): TokenResponse {
	return TokenResponseToJSONTyped(json, false);
}

export function TokenResponseToJSONTyped(
	value?: TokenResponse | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		access_token: value.accessToken,
		expires_in: value.expiresIn,
		refresh_token: value.refreshToken,
		token_type: value.tokenType,
	};
}
