/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Token is in a header (e.g., Authorization: Bearer <token>)
 * @export
 * @interface TokenLocationYamlOneOf
 */
export interface TokenLocationYamlOneOf {
	/**
	 *
	 * @type {string}
	 * @memberof TokenLocationYamlOneOf
	 */
	name: string;
	/**
	 *
	 * @type {string}
	 * @memberof TokenLocationYamlOneOf
	 */
	type: TokenLocationYamlOneOfTypeEnum;
}

/**
 * @export
 */
export const TokenLocationYamlOneOfTypeEnum = {
	Header: "header",
} as const;
export type TokenLocationYamlOneOfTypeEnum =
	(typeof TokenLocationYamlOneOfTypeEnum)[keyof typeof TokenLocationYamlOneOfTypeEnum];

/**
 * Check if a given object implements the TokenLocationYamlOneOf interface.
 */
export function instanceOfTokenLocationYamlOneOf(
	value: object,
): value is TokenLocationYamlOneOf {
	if (!("name" in value) || value.name === undefined) return false;
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function TokenLocationYamlOneOfFromJSON(
	json: any,
): TokenLocationYamlOneOf {
	return TokenLocationYamlOneOfFromJSONTyped(json, false);
}

export function TokenLocationYamlOneOfFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TokenLocationYamlOneOf {
	if (json == null) {
		return json;
	}
	return {
		name: json.name,
		type: json.type,
	};
}

export function TokenLocationYamlOneOfToJSON(
	json: any,
): TokenLocationYamlOneOf {
	return TokenLocationYamlOneOfToJSONTyped(json, false);
}

export function TokenLocationYamlOneOfToJSONTyped(
	value?: TokenLocationYamlOneOf | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		name: value.name,
		type: value.type,
	};
}
