/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateSecretRequest
 */
export interface UpdateSecretRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UpdateSecretRequest
	 */
	rawValue: string;
}

/**
 * Check if a given object implements the UpdateSecretRequest interface.
 */
export function instanceOfUpdateSecretRequest(
	value: object,
): value is UpdateSecretRequest {
	if (!("rawValue" in value) || value.rawValue === undefined) return false;
	return true;
}

export function UpdateSecretRequestFromJSON(json: any): UpdateSecretRequest {
	return UpdateSecretRequestFromJSONTyped(json, false);
}

export function UpdateSecretRequestFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): UpdateSecretRequest {
	if (json == null) {
		return json;
	}
	return {
		rawValue: json.raw_value,
	};
}

export function UpdateSecretRequestToJSON(json: any): UpdateSecretRequest {
	return UpdateSecretRequestToJSONTyped(json, false);
}

export function UpdateSecretRequestToJSONTyped(
	value?: UpdateSecretRequest | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		raw_value: value.rawValue,
	};
}
