/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateMcpServerInstanceRequest
 */
export interface UpdateMcpServerInstanceRequest {
	/**
	 *
	 * @type {string}
	 * @memberof UpdateMcpServerInstanceRequest
	 */
	name: string;
}

/**
 * Check if a given object implements the UpdateMcpServerInstanceRequest interface.
 */
export function instanceOfUpdateMcpServerInstanceRequest(
	value: object,
): value is UpdateMcpServerInstanceRequest {
	if (!("name" in value) || value.name === undefined) return false;
	return true;
}

export function UpdateMcpServerInstanceRequestFromJSON(
	json: any,
): UpdateMcpServerInstanceRequest {
	return UpdateMcpServerInstanceRequestFromJSONTyped(json, false);
}

export function UpdateMcpServerInstanceRequestFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): UpdateMcpServerInstanceRequest {
	if (json == null) {
		return json;
	}
	return {
		name: json.name,
	};
}

export function UpdateMcpServerInstanceRequestToJSON(
	json: any,
): UpdateMcpServerInstanceRequest {
	return UpdateMcpServerInstanceRequestToJSONTyped(json, false);
}

export function UpdateMcpServerInstanceRequestToJSONTyped(
	value?: UpdateMcpServerInstanceRequest | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		name: value.name,
	};
}
