/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncryptedOauthYamlConfig } from "./EncryptedOauthYamlConfig";
import {
	EncryptedOauthYamlConfigFromJSON,
	EncryptedOauthYamlConfigToJSON,
} from "./EncryptedOauthYamlConfig";

/**
 * OIDC authorization code flow with PKCE
 * @export
 * @interface UserAuthFlowYamlConfigOneOf2
 */
export interface UserAuthFlowYamlConfigOneOf2 {
	/**
	 * Base OAuth configuration
	 * @type {EncryptedOauthYamlConfig}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	baseConfig: EncryptedOauthYamlConfig;
	/**
	 * OIDC discovery endpoint (optional)
	 * @type {string}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	discoveryEndpoint?: string;
	/**
	 * Token introspection endpoint URL (RFC 7662) - if set, access tokens are treated as opaque
	 * @type {string}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	introspectUrl?: string;
	/**
	 *
	 * @type {any}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	mapping: any | null;
	/**
	 * Userinfo endpoint URL (optional)
	 * @type {string}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	userinfoEndpoint?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserAuthFlowYamlConfigOneOf2
	 */
	type: UserAuthFlowYamlConfigOneOf2TypeEnum;
}

/**
 * @export
 */
export const UserAuthFlowYamlConfigOneOf2TypeEnum = {
	OidcAuthorizationCodePkceFlow: "oidc_authorization_code_pkce_flow",
} as const;
export type UserAuthFlowYamlConfigOneOf2TypeEnum =
	(typeof UserAuthFlowYamlConfigOneOf2TypeEnum)[keyof typeof UserAuthFlowYamlConfigOneOf2TypeEnum];

/**
 * Check if a given object implements the UserAuthFlowYamlConfigOneOf2 interface.
 */
export function instanceOfUserAuthFlowYamlConfigOneOf2(
	value: object,
): value is UserAuthFlowYamlConfigOneOf2 {
	if (!("baseConfig" in value) || value.baseConfig === undefined) return false;
	if (!("mapping" in value) || value.mapping === undefined) return false;
	if (!("type" in value) || value.type === undefined) return false;
	return true;
}

export function UserAuthFlowYamlConfigOneOf2FromJSON(
	json: any,
): UserAuthFlowYamlConfigOneOf2 {
	return UserAuthFlowYamlConfigOneOf2FromJSONTyped(json, false);
}

export function UserAuthFlowYamlConfigOneOf2FromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): UserAuthFlowYamlConfigOneOf2 {
	if (json == null) {
		return json;
	}
	return {
		baseConfig: EncryptedOauthYamlConfigFromJSON(json.base_config),
		discoveryEndpoint:
			json.discovery_endpoint == null ? undefined : json.discovery_endpoint,
		introspectUrl:
			json.introspect_url == null ? undefined : json.introspect_url,
		mapping: json.mapping,
		userinfoEndpoint:
			json.userinfo_endpoint == null ? undefined : json.userinfo_endpoint,
		type: json.type,
	};
}

export function UserAuthFlowYamlConfigOneOf2ToJSON(
	json: any,
): UserAuthFlowYamlConfigOneOf2 {
	return UserAuthFlowYamlConfigOneOf2ToJSONTyped(json, false);
}

export function UserAuthFlowYamlConfigOneOf2ToJSONTyped(
	value?: UserAuthFlowYamlConfigOneOf2 | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		base_config: EncryptedOauthYamlConfigToJSON(value.baseConfig),
		discovery_endpoint: value.discoveryEndpoint,
		introspect_url: value.introspectUrl,
		mapping: value.mapping,
		userinfo_endpoint: value.userinfoEndpoint,
		type: value.type,
	};
}
