/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * An open source AI agent runtime
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OauthConfig } from "./OauthConfig";
import { OauthConfigFromJSON, OauthConfigToJSON } from "./OauthConfig";

/**
 *
 * @export
 * @interface UserAuthFlowConfigOneOf3
 */
export interface UserAuthFlowConfigOneOf3 {
	/**
	 *
	 * @type {string}
	 * @memberof UserAuthFlowConfigOneOf3
	 */
	type: UserAuthFlowConfigOneOf3TypeEnum;
	/**
	 *
	 * @type {OauthConfig}
	 * @memberof UserAuthFlowConfigOneOf3
	 */
	value: OauthConfig;
}

/**
 * @export
 */
export const UserAuthFlowConfigOneOf3TypeEnum = {
	OauthAuthorizationCodePkceFlow: "oauth_authorization_code_pkce_flow",
} as const;
export type UserAuthFlowConfigOneOf3TypeEnum =
	(typeof UserAuthFlowConfigOneOf3TypeEnum)[keyof typeof UserAuthFlowConfigOneOf3TypeEnum];

/**
 * Check if a given object implements the UserAuthFlowConfigOneOf3 interface.
 */
export function instanceOfUserAuthFlowConfigOneOf3(
	value: object,
): value is UserAuthFlowConfigOneOf3 {
	if (!("type" in value) || value.type === undefined) return false;
	if (!("value" in value) || value.value === undefined) return false;
	return true;
}

export function UserAuthFlowConfigOneOf3FromJSON(
	json: any,
): UserAuthFlowConfigOneOf3 {
	return UserAuthFlowConfigOneOf3FromJSONTyped(json, false);
}

export function UserAuthFlowConfigOneOf3FromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): UserAuthFlowConfigOneOf3 {
	if (json == null) {
		return json;
	}
	return {
		type: json.type,
		value: OauthConfigFromJSON(json.value),
	};
}

export function UserAuthFlowConfigOneOf3ToJSON(
	json: any,
): UserAuthFlowConfigOneOf3 {
	return UserAuthFlowConfigOneOf3ToJSONTyped(json, false);
}

export function UserAuthFlowConfigOneOf3ToJSONTyped(
	value?: UserAuthFlowConfigOneOf3 | null,
	_ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		type: value.type,
		value: OauthConfigToJSON(value.value),
	};
}
