/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum
 * Utoipa\'s axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCredentialBrokeringResponseOneOf1
 */
export interface UserCredentialBrokeringResponseOneOf1 {
    /**
     * 
     * @type {Date}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    dataEncryptionKeyId: string;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    nextRotationTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    typeId: string;
    /**
     * 
     * @type {Date}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    updatedAt: Date;
    /**
     * 
     * @type {any}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    value: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserCredentialBrokeringResponseOneOf1
     */
    type: UserCredentialBrokeringResponseOneOf1TypeEnum;
}


/**
 * @export
 */
export const UserCredentialBrokeringResponseOneOf1TypeEnum = {
    UserCredential: 'user_credential'
} as const;
export type UserCredentialBrokeringResponseOneOf1TypeEnum = typeof UserCredentialBrokeringResponseOneOf1TypeEnum[keyof typeof UserCredentialBrokeringResponseOneOf1TypeEnum];


/**
 * Check if a given object implements the UserCredentialBrokeringResponseOneOf1 interface.
 */
export function instanceOfUserCredentialBrokeringResponseOneOf1(value: object): value is UserCredentialBrokeringResponseOneOf1 {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('dataEncryptionKeyId' in value) || value['dataEncryptionKeyId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('typeId' in value) || value['typeId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UserCredentialBrokeringResponseOneOf1FromJSON(json: any): UserCredentialBrokeringResponseOneOf1 {
    return UserCredentialBrokeringResponseOneOf1FromJSONTyped(json, false);
}

export function UserCredentialBrokeringResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCredentialBrokeringResponseOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'dataEncryptionKeyId': json['data_encryption_key_id'],
        'id': json['id'],
        'metadata': json['metadata'],
        'nextRotationTime': json['next_rotation_time'] == null ? undefined : (new Date(json['next_rotation_time'])),
        'typeId': json['type_id'],
        'updatedAt': (new Date(json['updated_at'])),
        'value': json['value'],
        'type': json['type'],
    };
}

export function UserCredentialBrokeringResponseOneOf1ToJSON(json: any): UserCredentialBrokeringResponseOneOf1 {
    return UserCredentialBrokeringResponseOneOf1ToJSONTyped(json, false);
}

export function UserCredentialBrokeringResponseOneOf1ToJSONTyped(value?: UserCredentialBrokeringResponseOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'data_encryption_key_id': value['dataEncryptionKeyId'],
        'id': value['id'],
        'metadata': value['metadata'],
        'next_rotation_time': value['nextRotationTime'] == null ? undefined : ((value['nextRotationTime']).toISOString()),
        'type_id': value['typeId'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'value': value['value'],
        'type': value['type'],
    };
}

