// Auto-generated Bridge Client
// Do not edit this file manually

import type { ObjectContext } from '@restatedev/restate-sdk';

export interface BridgeConfig {
  SOMA_BASE_URL?: string;
}

interface InvokeResult<T> {
  type: 'success' | 'error';
  data?: T;
  error?: { message: string };
}

/**
 * Internal helper to invoke a bridge function
 */
async function invokeBridgeFunction<TParams, TResult>(
  ctx: ObjectContext,
  providerName: string,
  accountName: string,
  functionName: string,
  providerInstanceId: string,
  functionControllerTypeId: string,
  params: TParams,
  baseUrl: string
): Promise<TResult> {
  ctx.console.log(`Invoking ${providerName}.${accountName}.${functionName}`);

  const result = await ctx.run(`fetch-${providerName}-${functionName}`, async () => {
    const response = await fetch(
      `${baseUrl}/api/bridge/v1/provider/${providerInstanceId}/function/${functionControllerTypeId}/invoke`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ params }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`HTTP ${response.status}: ${errorText}`);
    }

    const result: InvokeResult<TResult> = await response.json();

    if (result.type === 'error') {
      throw new Error(result.error?.message || 'Unknown error');
    }

    return result.data as TResult;
  });

  ctx.console.log(`Completed ${providerName}.${accountName}.${functionName}`);
  return result;
}

// Type definitions for all functions



export type ApproveClaimApproveClaimParams = string;
export type ApproveClaimApproveClaimResult = string;





export type GoogleMailGoogleMailSendEmailParams = { body: string; subject: string; to: string };
export type GoogleMailGoogleMailSendEmailResult = { message_id: string };





// Provider: approveClaim
export interface ApproveClaimProvider {
  
  "internal": {
    
    approveClaim: (params: ApproveClaimApproveClaimParams) => Promise<ApproveClaimApproveClaimResult>;
    
  };
  
}

// Provider: googleMail
export interface GoogleMailProvider {
  
  "daniel@trysoma.ai": {
    
    sendEmail: (params: GoogleMailGoogleMailSendEmailParams) => Promise<GoogleMailGoogleMailSendEmailResult>;
    
  };
  
}


export interface Bridge {
  
  approveClaim: ApproveClaimProvider;
  
  googleMail: GoogleMailProvider;
  
}

export type BridgeDefinition = Bridge;

export function getBridge(ctx: ObjectContext, config?: BridgeConfig): Bridge {
  const baseUrl = config?.SOMA_BASE_URL || process.env.SOMA_SERVER_BASE_URL || 'http://localhost:3000';

  
  const approveClaim: ApproveClaimProvider = {
    
    "internal": {
      
      approveClaim: async (params: ApproveClaimApproveClaimParams): Promise<ApproveClaimApproveClaimResult> => {
        return invokeBridgeFunction<ApproveClaimApproveClaimParams, ApproveClaimApproveClaimResult>(
          ctx,
          'approveClaim',
          'internal',
          'approveClaim',
          '6acd6431-6f56-48b6-8fa7-acc56b990c22',
          'approve-claim',
          params,
          baseUrl
        );
      },
      
    },
    
  };
  
  const googleMail: GoogleMailProvider = {
    
    "daniel@trysoma.ai": {
      
      sendEmail: async (params: GoogleMailGoogleMailSendEmailParams): Promise<GoogleMailGoogleMailSendEmailResult> => {
        return invokeBridgeFunction<GoogleMailGoogleMailSendEmailParams, GoogleMailGoogleMailSendEmailResult>(
          ctx,
          'googleMail',
          'daniel@trysoma.ai',
          'sendEmail',
          '136e3705-6a55-42a3-881a-c4bad62db88c',
          'google_mail_send_email',
          params,
          baseUrl
        );
      },
      
    },
    
  };
  

  return {
    
    approveClaim,
    
    googleMail,
    
  };
}
