-- Empty schema - soma-api-server repository is no longer used
-- All database operations are handled by specialized crates:
-- - encryption crate for secrets
-- - environment crate for environment variables
-- - mcp crate for MCP server instances
-- - identity crate for authentication/authorization
