# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class JwtMappingConfigYaml(BaseModel):
    """
    JWT claim field mapping
    """  # noqa: E501

    audience_field: Optional[StrictStr] = Field(
        default=None, description='Field name for audience (default: "aud")'
    )
    email_field: Optional[StrictStr] = Field(
        default=None, description="Field name for email (optional)"
    )
    groups_field: Optional[StrictStr] = Field(
        default=None, description="Field name for groups (optional)"
    )
    issuer_field: Optional[StrictStr] = Field(
        default=None, description='Field name for issuer (default: "iss")'
    )
    scopes_field: Optional[StrictStr] = Field(
        default=None, description="Field name for scopes (optional)"
    )
    sub_field: Optional[StrictStr] = Field(
        default=None, description='Field name for subject (default: "sub")'
    )
    __properties: ClassVar[List[str]] = [
        "audience_field",
        "email_field",
        "groups_field",
        "issuer_field",
        "scopes_field",
        "sub_field",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JwtMappingConfigYaml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email_field (nullable) is None
        # and model_fields_set contains the field
        if self.email_field is None and "email_field" in self.model_fields_set:
            _dict["email_field"] = None

        # set to None if groups_field (nullable) is None
        # and model_fields_set contains the field
        if self.groups_field is None and "groups_field" in self.model_fields_set:
            _dict["groups_field"] = None

        # set to None if scopes_field (nullable) is None
        # and model_fields_set contains the field
        if self.scopes_field is None and "scopes_field" in self.model_fields_set:
            _dict["scopes_field"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JwtMappingConfigYaml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "audience_field": obj.get("audience_field"),
                "email_field": obj.get("email_field"),
                "groups_field": obj.get("groups_field"),
                "issuer_field": obj.get("issuer_field"),
                "scopes_field": obj.get("scopes_field"),
                "sub_field": obj.get("sub_field"),
            }
        )
        return _obj
