# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from trysoma_api_client.models.group_to_role_mapping_yaml import GroupToRoleMappingYaml
from trysoma_api_client.models.jwt_mapping_config_yaml import JwtMappingConfigYaml
from trysoma_api_client.models.jwt_validation_config_yaml import JwtValidationConfigYaml
from trysoma_api_client.models.scope_to_group_mapping_yaml import (
    ScopeToGroupMappingYaml,
)
from trysoma_api_client.models.scope_to_role_mapping_yaml import ScopeToRoleMappingYaml
from trysoma_api_client.models.token_location_yaml import TokenLocationYaml
from typing import Optional, Set
from typing_extensions import Self


class JwtTemplateConfigYaml(BaseModel):
    """
    JWT template configuration for validating external JWTs
    """  # noqa: E501

    group_to_role_mappings: Optional[List[GroupToRoleMappingYaml]] = Field(
        default=None, description="Group to role mappings"
    )
    jwks_uri: StrictStr = Field(description="JWKS URI to fetch public keys from")
    mapping: JwtMappingConfigYaml = Field(
        description="Field mapping from JWT claims to internal fields"
    )
    scope_to_group_mappings: Optional[List[ScopeToGroupMappingYaml]] = Field(
        default=None,
        description="Scope to group mappings (maps scopes to internal groups)",
    )
    scope_to_role_mappings: Optional[List[ScopeToRoleMappingYaml]] = Field(
        default=None, description="Scope to role mappings"
    )
    token_location: TokenLocationYaml = Field(
        description="Where to find the token in the request"
    )
    validation: JwtValidationConfigYaml = Field(description="Validation rules")
    __properties: ClassVar[List[str]] = [
        "group_to_role_mappings",
        "jwks_uri",
        "mapping",
        "scope_to_group_mappings",
        "scope_to_role_mappings",
        "token_location",
        "validation",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JwtTemplateConfigYaml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in group_to_role_mappings (list)
        _items = []
        if self.group_to_role_mappings:
            for _item_group_to_role_mappings in self.group_to_role_mappings:
                if _item_group_to_role_mappings:
                    _items.append(_item_group_to_role_mappings.to_dict())
            _dict["group_to_role_mappings"] = _items
        # override the default output from pydantic by calling `to_dict()` of mapping
        if self.mapping:
            _dict["mapping"] = self.mapping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in scope_to_group_mappings (list)
        _items = []
        if self.scope_to_group_mappings:
            for _item_scope_to_group_mappings in self.scope_to_group_mappings:
                if _item_scope_to_group_mappings:
                    _items.append(_item_scope_to_group_mappings.to_dict())
            _dict["scope_to_group_mappings"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in scope_to_role_mappings (list)
        _items = []
        if self.scope_to_role_mappings:
            for _item_scope_to_role_mappings in self.scope_to_role_mappings:
                if _item_scope_to_role_mappings:
                    _items.append(_item_scope_to_role_mappings.to_dict())
            _dict["scope_to_role_mappings"] = _items
        # override the default output from pydantic by calling `to_dict()` of token_location
        if self.token_location:
            _dict["token_location"] = self.token_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict["validation"] = self.validation.to_dict()
        # set to None if group_to_role_mappings (nullable) is None
        # and model_fields_set contains the field
        if (
            self.group_to_role_mappings is None
            and "group_to_role_mappings" in self.model_fields_set
        ):
            _dict["group_to_role_mappings"] = None

        # set to None if scope_to_group_mappings (nullable) is None
        # and model_fields_set contains the field
        if (
            self.scope_to_group_mappings is None
            and "scope_to_group_mappings" in self.model_fields_set
        ):
            _dict["scope_to_group_mappings"] = None

        # set to None if scope_to_role_mappings (nullable) is None
        # and model_fields_set contains the field
        if (
            self.scope_to_role_mappings is None
            and "scope_to_role_mappings" in self.model_fields_set
        ):
            _dict["scope_to_role_mappings"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JwtTemplateConfigYaml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "group_to_role_mappings": [
                    GroupToRoleMappingYaml.from_dict(_item)
                    for _item in obj["group_to_role_mappings"]
                ]
                if obj.get("group_to_role_mappings") is not None
                else None,
                "jwks_uri": obj.get("jwks_uri"),
                "mapping": JwtMappingConfigYaml.from_dict(obj["mapping"])
                if obj.get("mapping") is not None
                else None,
                "scope_to_group_mappings": [
                    ScopeToGroupMappingYaml.from_dict(_item)
                    for _item in obj["scope_to_group_mappings"]
                ]
                if obj.get("scope_to_group_mappings") is not None
                else None,
                "scope_to_role_mappings": [
                    ScopeToRoleMappingYaml.from_dict(_item)
                    for _item in obj["scope_to_role_mappings"]
                ]
                if obj.get("scope_to_role_mappings") is not None
                else None,
                "token_location": TokenLocationYaml.from_dict(obj["token_location"])
                if obj.get("token_location") is not None
                else None,
                "validation": JwtValidationConfigYaml.from_dict(obj["validation"])
                if obj.get("validation") is not None
                else None,
            }
        )
        return _obj
