# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictStr,
    ValidationError,
    field_validator,
)
from typing import Any, List, Optional
from trysoma_api_client.models.user_auth_flow_yaml_config_one_of import (
    UserAuthFlowYamlConfigOneOf,
)
from trysoma_api_client.models.user_auth_flow_yaml_config_one_of1 import (
    UserAuthFlowYamlConfigOneOf1,
)
from trysoma_api_client.models.user_auth_flow_yaml_config_one_of2 import (
    UserAuthFlowYamlConfigOneOf2,
)
from trysoma_api_client.models.user_auth_flow_yaml_config_one_of3 import (
    UserAuthFlowYamlConfigOneOf3,
)
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

USERAUTHFLOWYAMLCONFIG_ONE_OF_SCHEMAS = [
    "UserAuthFlowYamlConfigOneOf",
    "UserAuthFlowYamlConfigOneOf1",
    "UserAuthFlowYamlConfigOneOf2",
    "UserAuthFlowYamlConfigOneOf3",
]


class UserAuthFlowYamlConfig(BaseModel):
    """
    User auth flow configuration stored in soma.yaml (encrypted)
    """

    # data type: UserAuthFlowYamlConfigOneOf
    oneof_schema_1_validator: Optional[UserAuthFlowYamlConfigOneOf] = None
    # data type: UserAuthFlowYamlConfigOneOf1
    oneof_schema_2_validator: Optional[UserAuthFlowYamlConfigOneOf1] = None
    # data type: UserAuthFlowYamlConfigOneOf2
    oneof_schema_3_validator: Optional[UserAuthFlowYamlConfigOneOf2] = None
    # data type: UserAuthFlowYamlConfigOneOf3
    oneof_schema_4_validator: Optional[UserAuthFlowYamlConfigOneOf3] = None
    actual_instance: Optional[
        Union[
            UserAuthFlowYamlConfigOneOf,
            UserAuthFlowYamlConfigOneOf1,
            UserAuthFlowYamlConfigOneOf2,
            UserAuthFlowYamlConfigOneOf3,
        ]
    ] = None
    one_of_schemas: Set[str] = {
        "UserAuthFlowYamlConfigOneOf",
        "UserAuthFlowYamlConfigOneOf1",
        "UserAuthFlowYamlConfigOneOf2",
        "UserAuthFlowYamlConfigOneOf3",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = UserAuthFlowYamlConfig.model_construct()
        error_messages = []
        match = 0
        # validate data type: UserAuthFlowYamlConfigOneOf
        if not isinstance(v, UserAuthFlowYamlConfigOneOf):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `UserAuthFlowYamlConfigOneOf`"
            )
        else:
            match += 1
        # validate data type: UserAuthFlowYamlConfigOneOf1
        if not isinstance(v, UserAuthFlowYamlConfigOneOf1):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `UserAuthFlowYamlConfigOneOf1`"
            )
        else:
            match += 1
        # validate data type: UserAuthFlowYamlConfigOneOf2
        if not isinstance(v, UserAuthFlowYamlConfigOneOf2):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `UserAuthFlowYamlConfigOneOf2`"
            )
        else:
            match += 1
        # validate data type: UserAuthFlowYamlConfigOneOf3
        if not isinstance(v, UserAuthFlowYamlConfigOneOf3):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `UserAuthFlowYamlConfigOneOf3`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in UserAuthFlowYamlConfig with oneOf schemas: UserAuthFlowYamlConfigOneOf, UserAuthFlowYamlConfigOneOf1, UserAuthFlowYamlConfigOneOf2, UserAuthFlowYamlConfigOneOf3. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in UserAuthFlowYamlConfig with oneOf schemas: UserAuthFlowYamlConfigOneOf, UserAuthFlowYamlConfigOneOf1, UserAuthFlowYamlConfigOneOf2, UserAuthFlowYamlConfigOneOf3. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into UserAuthFlowYamlConfigOneOf
        try:
            instance.actual_instance = UserAuthFlowYamlConfigOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserAuthFlowYamlConfigOneOf1
        try:
            instance.actual_instance = UserAuthFlowYamlConfigOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserAuthFlowYamlConfigOneOf2
        try:
            instance.actual_instance = UserAuthFlowYamlConfigOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserAuthFlowYamlConfigOneOf3
        try:
            instance.actual_instance = UserAuthFlowYamlConfigOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into UserAuthFlowYamlConfig with oneOf schemas: UserAuthFlowYamlConfigOneOf, UserAuthFlowYamlConfigOneOf1, UserAuthFlowYamlConfigOneOf2, UserAuthFlowYamlConfigOneOf3. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into UserAuthFlowYamlConfig with oneOf schemas: UserAuthFlowYamlConfigOneOf, UserAuthFlowYamlConfigOneOf1, UserAuthFlowYamlConfigOneOf2, UserAuthFlowYamlConfigOneOf3. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[
            Dict[str, Any],
            UserAuthFlowYamlConfigOneOf,
            UserAuthFlowYamlConfigOneOf1,
            UserAuthFlowYamlConfigOneOf2,
            UserAuthFlowYamlConfigOneOf3,
        ]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
