// Auto-generated A2A Agent Clients
// Do not edit this file manually

import { A2AClient as BaseA2AClient } from "@a2a-js/sdk/client";
import type { ObjectContext } from "@restatedev/restate-sdk";
import {
	A2AClient,
	type A2AStreamEventData,
	type AgentCard,
	type CancelTaskResponse,
	type GetTaskResponse,
	type Message,
	type MessageSendParams,
	type SendMessageResponse,
	type Task,
	type TaskArtifactUpdateEvent,
	type TaskIdParams,
	type TaskQueryParams,
	type TaskStatusUpdateEvent,
} from "@trysoma/sdk/a2a";

export interface AgentsConfig {
	SOMA_BASE_URL?: string;
}

/**
 * Agent: Insurance Claims Agent
 * Project: acme
 * Description: An agent that can process insurance claims.
 */

/**
 * Agent: Claim Research Agent
 * Project: acme
 * Description: An agent that can research insurance claims.
 */

// Agent interface definitions

export interface AcmeAgents {
	insuranceClaimsAgent: A2AClient;

	claimResearchAgent: A2AClient;
}

export interface Agents {
	acme: AcmeAgents;
}

/**
 * Type alias for the agents definition.
 * Use this type when passing agents to pattern handlers.
 */
export type AgentsDefinition = Agents;

/**
 * Get all configured A2A agent clients, wrapped with Restate durability.
 *
 * @param ctx - The Restate ObjectContext for durability
 * @param config - Optional configuration including base URL
 * @returns An object containing all configured agents organized by project
 *
 * @example
 * ```typescript
 * const agents = await getAgents(ctx);
 *
 * // Send a message to an agent
 * const response = await agents.myProject.myAgent.sendMessage({
 *   message: {
 *     role: 'user',
 *     parts: [{ kind: 'text', text: 'Hello!' }],
 *     messageId: 'msg-123',
 *     kind: 'message'
 *   }
 * });
 *
 * // Stream responses from an agent
 * for await (const event of agents.myProject.myAgent.sendMessageStream({
 *   message: { ... }
 * })) {
 *   console.log('Received event:', event);
 * }
 * ```
 */
export async function getAgents(
	ctx: ObjectContext,
	config?: AgentsConfig,
): Promise<Agents> {
	const baseUrl =
		config?.SOMA_BASE_URL ||
		process.env.SOMA_SERVER_BASE_URL ||
		"http://localhost:3000";

	// Initialize all A2A clients

	const acme_insuranceClaimsAgentClient = await ctx.run(
		"init-a2a-acme-insuranceClaimsAgent",
		async () => {
			const cardUrl = `${baseUrl}/api/agent/acme/insuranceClaimsAgent/a2a/.well-known/agent.json`;
			return BaseA2AClient.fromCardUrl(cardUrl);
		},
	);
	const acme_insuranceClaimsAgent = new A2AClient(
		ctx,
		acme_insuranceClaimsAgentClient,
		"acme.insuranceClaimsAgent",
	);

	const acme_claimResearchAgentClient = await ctx.run(
		"init-a2a-acme-claimResearchAgent",
		async () => {
			const cardUrl = `${baseUrl}/api/agent/acme/claimResearchAgent/a2a/.well-known/agent.json`;
			return BaseA2AClient.fromCardUrl(cardUrl);
		},
	);
	const acme_claimResearchAgent = new A2AClient(
		ctx,
		acme_claimResearchAgentClient,
		"acme.claimResearchAgent",
	);

	return {
		acme: {
			insuranceClaimsAgent: acme_insuranceClaimsAgent,

			claimResearchAgent: acme_claimResearchAgent,
		},
	};
}

// Export types for external use
export type {
	AgentCard,
	MessageSendParams,
	SendMessageResponse,
	TaskQueryParams,
	GetTaskResponse,
	TaskIdParams,
	CancelTaskResponse,
	Message,
	Task,
	TaskStatusUpdateEvent,
	TaskArtifactUpdateEvent,
	A2AStreamEventData,
};
