// Auto-generated Bridge Client
// Do not edit this file manually

import type { ObjectContext } from '@restatedev/restate-sdk';

export interface BridgeConfig {
  SOMA_BASE_URL?: string;
}

interface InvokeResult<T> {
  type: 'success' | 'error';
  data?: T;
  error?: { message: string };
}

/**
 * Internal helper to invoke a bridge function
 */
async function invokeBridgeFunction<TParams, TResult>(
  ctx: ObjectContext,
  providerName: string,
  accountName: string,
  functionName: string,
  providerInstanceId: string,
  functionControllerTypeId: string,
  params: TParams,
  baseUrl: string
): Promise<TResult> {
  ctx.console.log(`Invoking ${providerName}.${accountName}.${functionName}`);

  const result = await ctx.run(`fetch-${providerName}-${functionName}`, async () => {
    const response = await fetch(
      `${baseUrl}/api/bridge/v1/provider/${providerInstanceId}/function/${functionControllerTypeId}/invoke`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ params }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`HTTP ${response.status}: ${errorText}`);
    }

    const result: InvokeResult<TResult> = await response.json();

    if (result.type === 'error') {
      throw new Error(result.error?.message || 'Unknown error');
    }

    return result.data as TResult;
  });

  ctx.console.log(`Completed ${providerName}.${accountName}.${functionName}`);
  return result;
}

// Type definitions for all functions



export type ResearchClaimResearchClaimParams = { claim: { amount: number; category: string; date: string; email: string; reason: string } };
export type ResearchClaimResearchClaimResult = { summary: string };





export type ApproveClaimApproveClaimParams = { claim: { amount: number; category: string; date: string; email: string; reason: string } };
export type ApproveClaimApproveClaimResult = { approved: boolean };





// Provider: research-claim
export interface ResearchClaim {
  
  "internal": {
    
    researchClaim: (params: ResearchClaimResearchClaimParams) => Promise<ResearchClaimResearchClaimResult>;
    
  };
  
}

// Provider: approve-claim
export interface ApproveClaim {
  
  "internal": {
    
    approveClaim: (params: ApproveClaimApproveClaimParams) => Promise<ApproveClaimApproveClaimResult>;
    
  };
  
}


export interface Bridge {
  
  researchClaim: ResearchClaim;
  
  approveClaim: ApproveClaim;
  
}

export type BridgeDefinition = Bridge;

export function getBridge(ctx: ObjectContext, config?: BridgeConfig): Bridge {
  const baseUrl = config?.SOMA_BASE_URL || process.env.SOMA_SERVER_BASE_URL || 'http://localhost:3000';
  
  const researchClaim: ResearchClaim = {
    
    "internal": {
      
      researchClaim: async (params: ResearchClaimResearchClaimParams): Promise<ResearchClaimResearchClaimResult> => {
        return invokeBridgeFunction<ResearchClaimResearchClaimParams, ResearchClaimResearchClaimResult>(
          ctx,
          'research-claim',
          'internal',
          'researchClaim',
          '452b1c4c-6ba7-4284-b362-2431750569fc',
          'research-claim',
          params,
          baseUrl
        );
      },
      
    },
    
  };
  
  const approveClaim: ApproveClaim = {
    
    "internal": {
      
      approveClaim: async (params: ApproveClaimApproveClaimParams): Promise<ApproveClaimApproveClaimResult> => {
        return invokeBridgeFunction<ApproveClaimApproveClaimParams, ApproveClaimApproveClaimResult>(
          ctx,
          'approve-claim',
          'internal',
          'approveClaim',
          '1b8c7dd2-45a9-4c82-8a9f-69cdb732883e',
          'approve-claim',
          params,
          baseUrl
        );
      },
      
    },
    
  };
  

  return {
    
    researchClaim: researchClaim,
    
    approveClaim: approveClaim,
    
  };
}
