# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.envelope_key_config_one_of import EnvelopeKeyConfigOneOf


class TestEnvelopeKeyConfigOneOf(unittest.TestCase):
    """EnvelopeKeyConfigOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeKeyConfigOneOf:
        """Test EnvelopeKeyConfigOneOf
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EnvelopeKeyConfigOneOf`
        """
        model = EnvelopeKeyConfigOneOf()
        if include_optional:
            return EnvelopeKeyConfigOneOf(
                arn = '',
                deks = {
                    'key' : trysoma_api_client.models.dek_config.DekConfig(
                        encrypted_key = '', )
                    },
                region = '',
                type = 'aws_kms'
            )
        else:
            return EnvelopeKeyConfigOneOf(
                arn = '',
                region = '',
                type = 'aws_kms',
        )
        """

    def testEnvelopeKeyConfigOneOf(self):
        """Test EnvelopeKeyConfigOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
