# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.configuration_schema import ConfigurationSchema


class TestConfigurationSchema(unittest.TestCase):
    """ConfigurationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationSchema:
        """Test ConfigurationSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConfigurationSchema`
        """
        model = ConfigurationSchema()
        if include_optional:
            return ConfigurationSchema(
                resource_server = {
                    'key' : null
                    },
                user_credential = {
                    'key' : null
                    }
            )
        else:
            return ConfigurationSchema(
                resource_server = {
                    'key' : null
                    },
                user_credential = {
                    'key' : null
                    },
        )
        """

    def testConfigurationSchema(self):
        """Test ConfigurationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
