# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.return_address_url import ReturnAddressUrl


class TestReturnAddressUrl(unittest.TestCase):
    """ReturnAddressUrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReturnAddressUrl:
        """Test ReturnAddressUrl
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReturnAddressUrl`
        """
        model = ReturnAddressUrl()
        if include_optional:
            return ReturnAddressUrl(
                url = ''
            )
        else:
            return ReturnAddressUrl(
                url = '',
        )
        """

    def testReturnAddressUrl(self):
        """Test ReturnAddressUrl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
