# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.list_environment_variables_response import (
    ListEnvironmentVariablesResponse,
)


class TestListEnvironmentVariablesResponse(unittest.TestCase):
    """ListEnvironmentVariablesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListEnvironmentVariablesResponse:
        """Test ListEnvironmentVariablesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListEnvironmentVariablesResponse`
        """
        model = ListEnvironmentVariablesResponse()
        if include_optional:
            return ListEnvironmentVariablesResponse(
                environment_variables = [
                    trysoma_api_client.models.environment_variable.EnvironmentVariable(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        key = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        value = '', )
                    ],
                next_page_token = ''
            )
        else:
            return ListEnvironmentVariablesResponse(
                environment_variables = [
                    trysoma_api_client.models.environment_variable.EnvironmentVariable(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        key = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        value = '', )
                    ],
        )
        """

    def testListEnvironmentVariablesResponse(self):
        """Test ListEnvironmentVariablesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
