# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.provider_credential_controller_serialized import (
    ProviderCredentialControllerSerialized,
)


class TestProviderCredentialControllerSerialized(unittest.TestCase):
    """ProviderCredentialControllerSerialized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderCredentialControllerSerialized:
        """Test ProviderCredentialControllerSerialized
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProviderCredentialControllerSerialized`
        """
        model = ProviderCredentialControllerSerialized()
        if include_optional:
            return ProviderCredentialControllerSerialized(
                configuration_schema = trysoma_api_client.models.configuration_schema.ConfigurationSchema(
                    resource_server = {
                        'key' : null
                        }, 
                    user_credential = {
                        'key' : null
                        }, ),
                documentation = '',
                name = '',
                requires_brokering = True,
                requires_resource_server_credential_refreshing = True,
                requires_user_credential_refreshing = True,
                type_id = ''
            )
        else:
            return ProviderCredentialControllerSerialized(
                configuration_schema = trysoma_api_client.models.configuration_schema.ConfigurationSchema(
                    resource_server = {
                        'key' : null
                        }, 
                    user_credential = {
                        'key' : null
                        }, ),
                documentation = '',
                name = '',
                requires_brokering = True,
                requires_resource_server_credential_refreshing = True,
                requires_user_credential_refreshing = True,
                type_id = '',
        )
        """

    def testProviderCredentialControllerSerialized(self):
        """Test ProviderCredentialControllerSerialized"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
