# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.task_timeline_item_paginated_response import (
    TaskTimelineItemPaginatedResponse,
)


class TestTaskTimelineItemPaginatedResponse(unittest.TestCase):
    """TaskTimelineItemPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskTimelineItemPaginatedResponse:
        """Test TaskTimelineItemPaginatedResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TaskTimelineItemPaginatedResponse`
        """
        model = TaskTimelineItemPaginatedResponse()
        if include_optional:
            return TaskTimelineItemPaginatedResponse(
                items = [
                    trysoma_api_client.models.task_timeline_item.TaskTimelineItem(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event_payload = null, 
                        id = '', 
                        task_id = '', )
                    ],
                next_page_token = ''
            )
        else:
            return TaskTimelineItemPaginatedResponse(
                items = [
                    trysoma_api_client.models.task_timeline_item.TaskTimelineItem(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event_payload = null, 
                        id = '', 
                        task_id = '', )
                    ],
        )
        """

    def testTaskTimelineItemPaginatedResponse(self):
        """Test TaskTimelineItemPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
