# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.context_info_paginated_response import (
    ContextInfoPaginatedResponse,
)


class TestContextInfoPaginatedResponse(unittest.TestCase):
    """ContextInfoPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContextInfoPaginatedResponse:
        """Test ContextInfoPaginatedResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ContextInfoPaginatedResponse`
        """
        model = ContextInfoPaginatedResponse()
        if include_optional:
            return ContextInfoPaginatedResponse(
                items = [
                    trysoma_api_client.models.context_info.ContextInfo(
                        context_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_page_token = ''
            )
        else:
            return ContextInfoPaginatedResponse(
                items = [
                    trysoma_api_client.models.context_info.ContextInfo(
                        context_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testContextInfoPaginatedResponse(self):
        """Test ContextInfoPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
