# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.provider_controller_serialized_paginated_response import (
    ProviderControllerSerializedPaginatedResponse,
)


class TestProviderControllerSerializedPaginatedResponse(unittest.TestCase):
    """ProviderControllerSerializedPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> ProviderControllerSerializedPaginatedResponse:
        """Test ProviderControllerSerializedPaginatedResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProviderControllerSerializedPaginatedResponse`
        """
        model = ProviderControllerSerializedPaginatedResponse()
        if include_optional:
            return ProviderControllerSerializedPaginatedResponse(
                items = [
                    trysoma_api_client.models.provider_controller_serialized.ProviderControllerSerialized(
                        categories = [
                            ''
                            ], 
                        credential_controllers = [
                            trysoma_api_client.models.provider_credential_controller_serialized.ProviderCredentialControllerSerialized(
                                configuration_schema = trysoma_api_client.models.configuration_schema.ConfigurationSchema(
                                    resource_server = {
                                        'key' : null
                                        }, 
                                    user_credential = {
                                        'key' : null
                                        }, ), 
                                documentation = '', 
                                name = '', 
                                requires_brokering = True, 
                                requires_resource_server_credential_refreshing = True, 
                                requires_user_credential_refreshing = True, 
                                type_id = '', )
                            ], 
                        documentation = '', 
                        functions = [
                            trysoma_api_client.models.function_controller_serialized.FunctionControllerSerialized(
                                categories = [
                                    ''
                                    ], 
                                documentation = '', 
                                name = '', 
                                output = , 
                                parameters = , 
                                type_id = '', )
                            ], 
                        name = '', 
                        type_id = '', )
                    ],
                next_page_token = ''
            )
        else:
            return ProviderControllerSerializedPaginatedResponse(
                items = [
                    trysoma_api_client.models.provider_controller_serialized.ProviderControllerSerialized(
                        categories = [
                            ''
                            ], 
                        credential_controllers = [
                            trysoma_api_client.models.provider_credential_controller_serialized.ProviderCredentialControllerSerialized(
                                configuration_schema = trysoma_api_client.models.configuration_schema.ConfigurationSchema(
                                    resource_server = {
                                        'key' : null
                                        }, 
                                    user_credential = {
                                        'key' : null
                                        }, ), 
                                documentation = '', 
                                name = '', 
                                requires_brokering = True, 
                                requires_resource_server_credential_refreshing = True, 
                                requires_user_credential_refreshing = True, 
                                type_id = '', )
                            ], 
                        documentation = '', 
                        functions = [
                            trysoma_api_client.models.function_controller_serialized.FunctionControllerSerialized(
                                categories = [
                                    ''
                                    ], 
                                documentation = '', 
                                name = '', 
                                output = , 
                                parameters = , 
                                type_id = '', )
                            ], 
                        name = '', 
                        type_id = '', )
                    ],
        )
        """

    def testProviderControllerSerializedPaginatedResponse(self):
        """Test ProviderControllerSerializedPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
