# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.api.bridge_api import BridgeApi


class TestBridgeApi(unittest.TestCase):
    """BridgeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BridgeApi()

    def tearDown(self) -> None:
        pass

    def test_create_provider_instance(self) -> None:
        """Test case for create_provider_instance

        Create provider
        """
        pass

    def test_create_resource_server_credential(self) -> None:
        """Test case for create_resource_server_credential

        Create resource server credential
        """
        pass

    def test_create_user_credential(self) -> None:
        """Test case for create_user_credential

        Create user credential
        """
        pass

    def test_delete_provider_instance(self) -> None:
        """Test case for delete_provider_instance

        Delete provider
        """
        pass

    def test_disable_function(self) -> None:
        """Test case for disable_function

        Disable function
        """
        pass

    def test_enable_function(self) -> None:
        """Test case for enable_function

        Enable function
        """
        pass

    def test_encrypt_resource_server_configuration(self) -> None:
        """Test case for encrypt_resource_server_configuration

        Encrypt resource server config
        """
        pass

    def test_encrypt_user_credential_configuration(self) -> None:
        """Test case for encrypt_user_credential_configuration

        Encrypt user credential config
        """
        pass

    def test_get_function_instances_openapi_spec(self) -> None:
        """Test case for get_function_instances_openapi_spec

        Get function OpenAPI spec
        """
        pass

    def test_get_provider_instance(self) -> None:
        """Test case for get_provider_instance

        Get provider
        """
        pass

    def test_invoke_function(self) -> None:
        """Test case for invoke_function

        Invoke function
        """
        pass

    def test_list_available_providers(self) -> None:
        """Test case for list_available_providers

        List providers
        """
        pass

    def test_list_function_instances(self) -> None:
        """Test case for list_function_instances

        List function instances
        """
        pass

    def test_list_provider_instances(self) -> None:
        """Test case for list_provider_instances

        List provider instances
        """
        pass

    def test_list_provider_instances_grouped_by_function(self) -> None:
        """Test case for list_provider_instances_grouped_by_function

        List providers by function
        """
        pass

    def test_listen_to_mcp_sse(self) -> None:
        """Test case for listen_to_mcp_sse

        MCP SSE connection
        """
        pass

    def test_resume_user_credential_brokering(self) -> None:
        """Test case for resume_user_credential_brokering

        OAuth callback
        """
        pass

    def test_start_user_credential_brokering(self) -> None:
        """Test case for start_user_credential_brokering

        Start credential brokering
        """
        pass

    def test_trigger_mcp_message(self) -> None:
        """Test case for trigger_mcp_message

        Send MCP message
        """
        pass

    def test_update_provider_instance(self) -> None:
        """Test case for update_provider_instance

        Update provider
        """
        pass


if __name__ == "__main__":
    unittest.main()
