# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.models.data_encryption_key_alias import DataEncryptionKeyAlias


class TestDataEncryptionKeyAlias(unittest.TestCase):
    """DataEncryptionKeyAlias unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataEncryptionKeyAlias:
        """Test DataEncryptionKeyAlias
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DataEncryptionKeyAlias`
        """
        model = DataEncryptionKeyAlias()
        if include_optional:
            return DataEncryptionKeyAlias(
                alias = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_encryption_key_id = ''
            )
        else:
            return DataEncryptionKeyAlias(
                alias = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_encryption_key_id = '',
        )
        """

    def testDataEncryptionKeyAlias(self):
        """Test DataEncryptionKeyAlias"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
