# coding: utf-8

"""
soma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from trysoma_api_client.api.a2a_api import A2aApi


class TestA2aApi(unittest.TestCase):
    """A2aApi unit test stubs"""

    def setUp(self) -> None:
        self.api = A2aApi()

    def tearDown(self) -> None:
        pass

    def test_get_agent_card(self) -> None:
        """Test case for get_agent_card

        Get agent card
        """
        pass

    def test_get_agent_definition(self) -> None:
        """Test case for get_agent_definition

        Get agent definition
        """
        pass

    def test_get_extended_agent_card(self) -> None:
        """Test case for get_extended_agent_card

        Get extended agent card
        """
        pass

    def test_handle_jsonrpc_request(self) -> None:
        """Test case for handle_jsonrpc_request

        Handle JSON-RPC
        """
        pass


if __name__ == "__main__":
    unittest.main()
