name: 'Setup uv and Python'
description: 'Sets up uv package manager and Python with caching configured'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  uv-version:
    description: 'uv version to install'
    required: false
    default: 'latest'
  working-directory:
    description: 'Working directory for uv commands'
    required: false
    default: 'py'
  install-dependencies:
    description: 'Whether to run uv sync'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        cache-dependency-glob: |
          ${{ inputs.working-directory }}/uv.lock
          ${{ inputs.working-directory }}/**/pyproject.toml

    - name: Setup Python
      shell: bash
      run: |
        uv python install ${{ inputs.python-version }}
        echo "Python ${{ inputs.python-version }} installed via uv"

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        uv sync --all-packages
        echo "✓ Python dependencies installed"
