from typing import Callable

import typing

class Agent:
    def __new__(cls, id: str, project_id: str, name: str, description: str, /) -> Agent: ...
    @property
    def description(self, /) -> str: ...
    @description.setter
    def description(self, /, value: str) -> None: ...
    @property
    def id(self, /) -> str: ...
    @id.setter
    def id(self, /, value: str) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def project_id(self, /) -> str: ...
    @project_id.setter
    def project_id(self, /, value: str) -> None: ...

class CallbackError:
    def __new__(cls, message: str, /) -> CallbackError: ...
    @property
    def message(self, /) -> str: ...
    @message.setter
    def message(self, /, value: str) -> None: ...

class EnvironmentVariable:
    def __new__(cls, key: str, value: str, /) -> EnvironmentVariable: ...
    @property
    def key(self, /) -> str: ...
    @key.setter
    def key(self, /, value: str) -> None: ...
    @property
    def value(self, /) -> str: ...
    @value.setter
    def value(self, /, value: str) -> None: ...

class FunctionController:
    def __new__(cls, name: str, description: str, parameters: str, output: str, /) -> FunctionController: ...
    @property
    def description(self, /) -> str: ...
    @description.setter
    def description(self, /, value: str) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def output(self, /) -> str: ...
    @output.setter
    def output(self, /, value: str) -> None: ...
    @property
    def parameters(self, /) -> str: ...
    @parameters.setter
    def parameters(self, /, value: str) -> None: ...

class FunctionMetadata:
    def __new__(cls, name: str, description: str, parameters: str, output: str, /) -> FunctionMetadata: ...
    @property
    def description(self, /) -> str: ...
    @description.setter
    def description(self, /, value: str) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def output(self, /) -> str: ...
    @output.setter
    def output(self, /, value: str) -> None: ...
    @property
    def parameters(self, /) -> str: ...
    @parameters.setter
    def parameters(self, /, value: str) -> None: ...

class InvokeFunctionRequest:
    def __new__(cls, provider_controller_type_id: str, function_controller_type_id: str, credential_controller_type_id: str, credentials: str, parameters: str, /) -> InvokeFunctionRequest: ...
    @property
    def credential_controller_type_id(self, /) -> str: ...
    @credential_controller_type_id.setter
    def credential_controller_type_id(self, /, value: str) -> None: ...
    @property
    def credentials(self, /) -> str: ...
    @credentials.setter
    def credentials(self, /, value: str) -> None: ...
    @property
    def function_controller_type_id(self, /) -> str: ...
    @function_controller_type_id.setter
    def function_controller_type_id(self, /, value: str) -> None: ...
    @property
    def parameters(self, /) -> str: ...
    @parameters.setter
    def parameters(self, /, value: str) -> None: ...
    @property
    def provider_controller_type_id(self, /) -> str: ...
    @provider_controller_type_id.setter
    def provider_controller_type_id(self, /, value: str) -> None: ...

class InvokeFunctionResponse:
    def __new__(cls, /, data: str | None = None, error: CallbackError | None = None) -> InvokeFunctionResponse: ...
    @property
    def data(self, /) -> typing.Any: ...
    @data.setter
    def data(self, /, value: typing.Any) -> None: ...
    @property
    def error(self, /) -> typing.Any: ...
    @error.setter
    def error(self, /, value: typing.Any) -> None: ...
    @staticmethod
    def failure(message: str, /) -> InvokeFunctionResponse: ...
    @staticmethod
    def success(data: str, /) -> InvokeFunctionResponse: ...

class Metadata:
    def __new__(cls, key: str, value: str, /) -> Metadata: ...
    @property
    def key(self, /) -> str: ...
    @key.setter
    def key(self, /, value: str) -> None: ...
    @property
    def value(self, /) -> str: ...
    @value.setter
    def value(self, /, value: str) -> None: ...

class Oauth2AuthorizationCodeFlowConfiguration:
    def __new__(cls, static_credential_configuration: Oauth2AuthorizationCodeFlowStaticCredentialConfiguration, /) -> Oauth2AuthorizationCodeFlowConfiguration: ...
    @property
    def static_credential_configuration(self, /) -> Oauth2AuthorizationCodeFlowStaticCredentialConfiguration: ...
    @static_credential_configuration.setter
    def static_credential_configuration(self, /, value: Oauth2AuthorizationCodeFlowStaticCredentialConfiguration) -> None: ...

class Oauth2AuthorizationCodeFlowStaticCredentialConfiguration:
    def __new__(cls, auth_uri: str, token_uri: str, userinfo_uri: str, jwks_uri: str, issuer: str, scopes: list[str], /, metadata: list[Metadata] | None = None) -> Oauth2AuthorizationCodeFlowStaticCredentialConfiguration: ...
    @property
    def auth_uri(self, /) -> str: ...
    @auth_uri.setter
    def auth_uri(self, /, value: str) -> None: ...
    @property
    def issuer(self, /) -> str: ...
    @issuer.setter
    def issuer(self, /, value: str) -> None: ...
    @property
    def jwks_uri(self, /) -> str: ...
    @jwks_uri.setter
    def jwks_uri(self, /, value: str) -> None: ...
    @property
    def metadata(self, /) -> typing.Any: ...
    @metadata.setter
    def metadata(self, /, value: typing.Any) -> None: ...
    @property
    def scopes(self, /) -> typing.Any: ...
    @scopes.setter
    def scopes(self, /, value: typing.Any) -> None: ...
    @property
    def token_uri(self, /) -> str: ...
    @token_uri.setter
    def token_uri(self, /, value: str) -> None: ...
    @property
    def userinfo_uri(self, /) -> str: ...
    @userinfo_uri.setter
    def userinfo_uri(self, /, value: str) -> None: ...

class Oauth2JwtBearerAssertionFlowConfiguration:
    def __new__(cls, static_credential_configuration: Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration, /) -> Oauth2JwtBearerAssertionFlowConfiguration: ...
    @property
    def static_credential_configuration(self, /) -> Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration: ...
    @static_credential_configuration.setter
    def static_credential_configuration(self, /, value: Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration) -> None: ...

class Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration:
    def __new__(cls, auth_uri: str, token_uri: str, userinfo_uri: str, jwks_uri: str, issuer: str, scopes: list[str], /, metadata: list[Metadata] | None = None) -> Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration: ...
    @property
    def auth_uri(self, /) -> str: ...
    @auth_uri.setter
    def auth_uri(self, /, value: str) -> None: ...
    @property
    def issuer(self, /) -> str: ...
    @issuer.setter
    def issuer(self, /, value: str) -> None: ...
    @property
    def jwks_uri(self, /) -> str: ...
    @jwks_uri.setter
    def jwks_uri(self, /, value: str) -> None: ...
    @property
    def metadata(self, /) -> typing.Any: ...
    @metadata.setter
    def metadata(self, /, value: typing.Any) -> None: ...
    @property
    def scopes(self, /) -> typing.Any: ...
    @scopes.setter
    def scopes(self, /, value: typing.Any) -> None: ...
    @property
    def token_uri(self, /) -> str: ...
    @token_uri.setter
    def token_uri(self, /, value: str) -> None: ...
    @property
    def userinfo_uri(self, /) -> str: ...
    @userinfo_uri.setter
    def userinfo_uri(self, /, value: str) -> None: ...

class ProviderController:
    def __new__(cls, type_id: str, name: str, documentation: str, categories: list[str], credential_controllers: list[ProviderCredentialController], /) -> ProviderController: ...
    @property
    def categories(self, /) -> typing.Any: ...
    @categories.setter
    def categories(self, /, value: typing.Any) -> None: ...
    @property
    def credential_controllers(self, /) -> typing.Any: ...
    @credential_controllers.setter
    def credential_controllers(self, /, value: typing.Any) -> None: ...
    @property
    def documentation(self, /) -> str: ...
    @documentation.setter
    def documentation(self, /, value: str) -> None: ...
    @property
    def name(self, /) -> str: ...
    @name.setter
    def name(self, /, value: str) -> None: ...
    @property
    def type_id(self, /) -> str: ...
    @type_id.setter
    def type_id(self, /, value: str) -> None: ...

class ProviderCredentialController:
    @staticmethod
    def api_key() -> ProviderCredentialController: ...
    @property
    def credential_type(self, /) -> str: ...
    def get_oauth2_authorization_code_config(self, /) -> Oauth2AuthorizationCodeFlowConfiguration | None: ...
    def get_oauth2_jwt_bearer_config(self, /) -> Oauth2JwtBearerAssertionFlowConfiguration | None: ...
    @staticmethod
    def no_auth() -> ProviderCredentialController: ...
    @staticmethod
    def oauth2_authorization_code_flow(config: Oauth2AuthorizationCodeFlowConfiguration, /) -> ProviderCredentialController: ...
    @staticmethod
    def oauth2_jwt_bearer_flow(config: Oauth2JwtBearerAssertionFlowConfiguration, /) -> ProviderCredentialController: ...

class Secret:
    def __new__(cls, key: str, value: str, /) -> Secret: ...
    @property
    def key(self, /) -> str: ...
    @key.setter
    def key(self, /, value: str) -> None: ...
    @property
    def value(self, /) -> str: ...
    @value.setter
    def value(self, /, value: str) -> None: ...

class SetEnvironmentVariablesResponse:
    def __new__(cls, /, data: SetEnvironmentVariablesSuccess | None = None, error: CallbackError | None = None) -> SetEnvironmentVariablesResponse: ...
    @property
    def data(self, /) -> typing.Any: ...
    @data.setter
    def data(self, /, value: typing.Any) -> None: ...
    @property
    def error(self, /) -> typing.Any: ...
    @error.setter
    def error(self, /, value: typing.Any) -> None: ...
    @staticmethod
    def failure(message: str, /) -> SetEnvironmentVariablesResponse: ...
    @staticmethod
    def success(message: str, /) -> SetEnvironmentVariablesResponse: ...

class SetEnvironmentVariablesSuccess:
    def __new__(cls, message: str, /) -> SetEnvironmentVariablesSuccess: ...
    @property
    def message(self, /) -> str: ...
    @message.setter
    def message(self, /, value: str) -> None: ...

class SetSecretsResponse:
    def __new__(cls, /, data: SetSecretsSuccess | None = None, error: CallbackError | None = None) -> SetSecretsResponse: ...
    @property
    def data(self, /) -> typing.Any: ...
    @data.setter
    def data(self, /, value: typing.Any) -> None: ...
    @property
    def error(self, /) -> typing.Any: ...
    @error.setter
    def error(self, /, value: typing.Any) -> None: ...
    @staticmethod
    def failure(message: str, /) -> SetSecretsResponse: ...
    @staticmethod
    def success(message: str, /) -> SetSecretsResponse: ...

class SetSecretsSuccess:
    def __new__(cls, message: str, /) -> SetSecretsSuccess: ...
    @property
    def message(self, /) -> str: ...
    @message.setter
    def message(self, /, value: str) -> None: ...

class UnsetEnvironmentVariableResponse:
    def __new__(cls, /, data: UnsetEnvironmentVariableSuccess | None = None, error: CallbackError | None = None) -> UnsetEnvironmentVariableResponse: ...
    @property
    def data(self, /) -> typing.Any: ...
    @data.setter
    def data(self, /, value: typing.Any) -> None: ...
    @property
    def error(self, /) -> typing.Any: ...
    @error.setter
    def error(self, /, value: typing.Any) -> None: ...
    @staticmethod
    def failure(message: str, /) -> UnsetEnvironmentVariableResponse: ...
    @staticmethod
    def success(message: str, /) -> UnsetEnvironmentVariableResponse: ...

class UnsetEnvironmentVariableSuccess:
    def __new__(cls, message: str, /) -> UnsetEnvironmentVariableSuccess: ...
    @property
    def message(self, /) -> str: ...
    @message.setter
    def message(self, /, value: str) -> None: ...

class UnsetSecretResponse:
    def __new__(cls, /, data: UnsetSecretSuccess | None = None, error: CallbackError | None = None) -> UnsetSecretResponse: ...
    @property
    def data(self, /) -> typing.Any: ...
    @data.setter
    def data(self, /, value: typing.Any) -> None: ...
    @property
    def error(self, /) -> typing.Any: ...
    @error.setter
    def error(self, /, value: typing.Any) -> None: ...
    @staticmethod
    def failure(message: str, /) -> UnsetSecretResponse: ...
    @staticmethod
    def success(message: str, /) -> UnsetSecretResponse: ...

class UnsetSecretSuccess:
    def __new__(cls, message: str, /) -> UnsetSecretSuccess: ...
    @property
    def message(self, /) -> str: ...
    @message.setter
    def message(self, /, value: str) -> None: ...

def add_agent(agent: Agent, /) -> bool: ...
def add_provider(provider: ProviderController, /) -> None: ...
def remove_agent(id: str, /) -> bool: ...
def remove_function(provider_type_id: str, function_name: str, /) -> bool: ...
def remove_provider(type_id: str, /) -> bool: ...
def resync_sdk(base_url: str | None = None) -> typing.Awaitable[None]: ...
def set_environment_variable_handler(callback: Callable[[list[EnvironmentVariable]], SetEnvironmentVariablesResponse], /) -> None: ...
def set_secret_handler(callback: Callable[[list[Secret]], SetSecretsResponse], /) -> None: ...
def set_unset_environment_variable_handler(callback: Callable[[str], UnsetEnvironmentVariableResponse], /) -> None: ...
def set_unset_secret_handler(callback: Callable[[str], UnsetSecretResponse], /) -> None: ...
def start_grpc_server(socket_path: str, project_dir: str, /) -> typing.Awaitable[None]: ...
def update_agent(agent: Agent, /) -> bool: ...
def update_function(provider_type_id: str, function_metadata: FunctionMetadata, invoke_callback: typing.Callable[[InvokeFunctionRequest], InvokeFunctionResponse], /) -> bool: ...
def update_provider(provider: ProviderController, /) -> bool: ...
