/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class InvokeFunctionRequest {
	providerControllerTypeId: string;
	functionControllerTypeId: string;
	credentialControllerTypeId: string;
	credentials: string;
	parameters: string;
}

export declare function addAgent(agent: Agent): boolean;

export declare function addFunction(
	providerTypeId: string,
	functionMetadata: FunctionMetadata,
	invokeCallback: (
		err: Error | null,
		arg: InvokeFunctionRequest,
	) => Promise<InvokeFunctionResponse>,
): boolean;

/** Add a provider controller to the running server */
export declare function addProvider(provider: ProviderController): void;

export interface Agent {
	id: string;
	projectId: string;
	name: string;
	description: string;
}

export interface FunctionController {
	name: string;
	description: string;
	parameters: string;
	output: string;
}

export interface FunctionControllerData {
	typeId: string;
	displayName: string;
	paramsJsonSchema: string;
	returnValueJsonSchema: string;
}

export interface FunctionInstanceData {
	providerInstanceId: string;
	providerInstanceDisplayName: string;
	providerController?: ProviderControllerData;
	functionController?: FunctionControllerData;
}

/**
 * Add a function controller to a specific provider
 *
 * # Parameters
 * * `provider_type_id` - The type_id of the provider to add the function to
 * * `function_metadata` - Object containing name, description, parameters, and output
 * * `invoke_callback` - ThreadsafeFunction that will be called when the function is invoked
 */
export interface FunctionMetadata {
	name: string;
	description: string;
	parameters: string;
	output: string;
}

export interface GenerateBridgeClientError {
	message: string;
}

export interface GenerateBridgeClientRequest {
	functionInstances: Array<FunctionInstanceData>;
}

export interface GenerateBridgeClientResponse {
	success?: GenerateBridgeClientSuccess;
	error?: GenerateBridgeClientError;
}

export interface GenerateBridgeClientSuccess {
	message: string;
}

export interface InvokeError {
	message: string;
}

export interface InvokeFunctionResponse {
	data?: string;
	error?: InvokeError;
}

export interface Metadata {
	key: string;
	value: string;
}

export interface Oauth2AuthorizationCodeFlowConfiguration {
	staticCredentialConfiguration: Oauth2AuthorizationCodeFlowStaticCredentialConfiguration;
}

export interface Oauth2AuthorizationCodeFlowStaticCredentialConfiguration {
	authUri: string;
	tokenUri: string;
	userinfoUri: string;
	jwksUri: string;
	issuer: string;
	scopes: Array<string>;
	metadata?: Array<Metadata>;
}

export interface Oauth2JwtBearerAssertionFlowConfiguration {
	staticCredentialConfiguration: Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration;
}

export interface Oauth2JwtBearerAssertionFlowStaticCredentialConfiguration {
	authUri: string;
	tokenUri: string;
	userinfoUri: string;
	jwksUri: string;
	issuer: string;
	scopes: Array<string>;
	metadata?: Array<Metadata>;
}

export interface ProviderController {
	typeId: string;
	name: string;
	documentation: string;
	categories: Array<string>;
	credentialControllers: Array<ProviderCredentialController>;
}

export interface ProviderControllerData {
	typeId: string;
	displayName: string;
}

export type ProviderCredentialController =
	| { type: "NoAuth" }
	| { type: "ApiKey" }
	| {
			type: "Oauth2AuthorizationCodeFlow";
			field0: Oauth2AuthorizationCodeFlowConfiguration;
	  }
	| {
			type: "Oauth2JwtBearerAssertionFlow";
			field0: Oauth2JwtBearerAssertionFlowConfiguration;
	  };

/** Remove an agent by id */
export declare function removeAgent(id: string): boolean;

/** Remove a function controller from a specific provider */
export declare function removeFunction(
	providerTypeId: string,
	functionName: string,
): boolean;

/** Remove a provider controller by type_id */
export declare function removeProvider(typeId: string): boolean;

/** Start the gRPC server on a Unix socket with TypeScript code generation */
export declare function startGrpcServer(
	socketPath: string,
	projectDir: string,
): Promise<void>;

/** Update an agent (removes old and inserts new) */
export declare function updateAgent(agent: Agent): boolean;

/** Update a function controller (removes old and inserts new) */
export declare function updateFunction(
	providerTypeId: string,
	functionMetadata: FunctionMetadata,
	invokeCallback: (
		err: Error | null,
		arg: InvokeFunctionRequest,
	) => InvokeFunctionResponse,
): boolean;

/** Update a provider controller (removes old and inserts new) */
export declare function updateProvider(provider: ProviderController): boolean;
