/* tslint:disable */
/* eslint-disable */
/**
 * soma
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SomaAgentDefinition } from "../models/index";
import { SomaAgentDefinitionFromJSON } from "../models/index";
import * as runtime from "../runtime";

export interface A2aApiGetAgentCardRequest {
	projectId: string;
	agentId: string;
}

export interface A2aApiHandleJsonrpcRequestRequest {
	projectId: string;
	agentId: string;
	body: object;
}

/**
 *
 */
export class A2aApi extends runtime.BaseAPI {
	/**
	 * Get the agent card describing agent capabilities and metadata for a specific agent
	 * Get agent card for specific agent
	 */
	async getAgentCardRaw(
		requestParameters: A2aApiGetAgentCardRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<object>> {
		if (requestParameters.projectId == null) {
			throw new runtime.RequiredError(
				"projectId",
				'Required parameter "projectId" was null or undefined when calling getAgentCard().',
			);
		}

		if (requestParameters.agentId == null) {
			throw new runtime.RequiredError(
				"agentId",
				'Required parameter "agentId" was null or undefined when calling getAgentCard().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/api/a2a/v1/{project_id}/{agent_id}/.well-known/agent.json`;
		urlPath = urlPath.replace(
			`{${"project_id"}}`,
			encodeURIComponent(String(requestParameters.projectId)),
		);
		urlPath = urlPath.replace(
			`{${"agent_id"}}`,
			encodeURIComponent(String(requestParameters.agentId)),
		);

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse<any>(response);
	}

	/**
	 * Get the agent card describing agent capabilities and metadata for a specific agent
	 * Get agent card for specific agent
	 */
	async getAgentCard(
		requestParameters: A2aApiGetAgentCardRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<object> {
		const response = await this.getAgentCardRaw(
			requestParameters,
			initOverrides,
		);
		return await response.value();
	}

	/**
	 * Get the agent definition (capabilities and metadata)
	 * Get agent definition
	 */
	async getAgentDefinitionRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<SomaAgentDefinition>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		const urlPath = `/api/a2a/v1/definition`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			SomaAgentDefinitionFromJSON(jsonValue),
		);
	}

	/**
	 * Get the agent definition (capabilities and metadata)
	 * Get agent definition
	 */
	async getAgentDefinition(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<SomaAgentDefinition> {
		const response = await this.getAgentDefinitionRaw(initOverrides);
		return await response.value();
	}

	/**
	 * Handle JSON-RPC requests for agent-to-agent communication for a specific agent
	 * Handle JSON-RPC for specific agent
	 */
	async handleJsonrpcRequestRaw(
		requestParameters: A2aApiHandleJsonrpcRequestRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters.projectId == null) {
			throw new runtime.RequiredError(
				"projectId",
				'Required parameter "projectId" was null or undefined when calling handleJsonrpcRequest().',
			);
		}

		if (requestParameters.agentId == null) {
			throw new runtime.RequiredError(
				"agentId",
				'Required parameter "agentId" was null or undefined when calling handleJsonrpcRequest().',
			);
		}

		if (requestParameters.body == null) {
			throw new runtime.RequiredError(
				"body",
				'Required parameter "body" was null or undefined when calling handleJsonrpcRequest().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		let urlPath = `/api/a2a/v1/{project_id}/{agent_id}`;
		urlPath = urlPath.replace(
			`{${"project_id"}}`,
			encodeURIComponent(String(requestParameters.projectId)),
		);
		urlPath = urlPath.replace(
			`{${"agent_id"}}`,
			encodeURIComponent(String(requestParameters.agentId)),
		);

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: requestParameters.body as any,
			},
			initOverrides,
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 * Handle JSON-RPC requests for agent-to-agent communication for a specific agent
	 * Handle JSON-RPC for specific agent
	 */
	async handleJsonrpcRequest(
		requestParameters: A2aApiHandleJsonrpcRequestRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<void> {
		await this.handleJsonrpcRequestRaw(requestParameters, initOverrides);
	}
}
