/*
 * utoipa-axum
 *
 * Utoipa's axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMessageRequest {
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "parts")]
    pub parts: Vec<models::MessagePart>,
    #[serde(rename = "reference_task_ids")]
    pub reference_task_ids: Vec<uuid::Uuid>,
    #[serde(rename = "role")]
    pub role: models::MessageRole,
}

impl CreateMessageRequest {
    pub fn new(metadata: std::collections::HashMap<String, serde_json::Value>, parts: Vec<models::MessagePart>, reference_task_ids: Vec<uuid::Uuid>, role: models::MessageRole) -> CreateMessageRequest {
        CreateMessageRequest {
            metadata,
            parts,
            reference_task_ids,
            role,
        }
    }
}

