/*
 * utoipa-axum
 *
 * Utoipa's axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptCredentialConfigurationParamsInner {
    #[serde(rename = "data_encryption_key_id")]
    pub data_encryption_key_id: String,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
}

impl EncryptCredentialConfigurationParamsInner {
    pub fn new(data_encryption_key_id: String, value: Option<serde_json::Value>) -> EncryptCredentialConfigurationParamsInner {
        EncryptCredentialConfigurationParamsInner {
            data_encryption_key_id,
            value,
        }
    }
}

