/*
 * utoipa-axum
 *
 * Utoipa's axum bindings for seamless integration for the two
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: juha7kukkonen@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvelopeEncryptionKeyIdOneOf1 {
    #[serde(rename = "key_id")]
    pub key_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl EnvelopeEncryptionKeyIdOneOf1 {
    pub fn new(key_id: String, r#type: Type) -> EnvelopeEncryptionKeyIdOneOf1 {
        EnvelopeEncryptionKeyIdOneOf1 {
            key_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "local")]
    Local,
}

impl Default for Type {
    fn default() -> Type {
        Self::Local
    }
}

